---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    # From: curl https://raw.githubusercontent.com/longhorn/longhorn/v1.11.2/deploy/longhorn-images.txt
    image-lock/extra-images: >-
      longhornio/backing-image-manager:v1.11.2,
      longhornio/longhorn-engine:v1.11.2,
      longhornio/longhorn-instance-manager:v1.11.2,
      longhornio/longhorn-manager:v1.11.2,
      longhornio/longhorn-share-manager:v1.11.2,
      longhornio/longhorn-ui:v1.11.2,
      longhornio/longhorn-cli:v1.11.2,
      longhornio/csi-attacher:v4.11.0-20260428,
      longhornio/csi-provisioner:v5.3.0-20260428,
      longhornio/csi-resizer:v2.1.0-20260428,
      longhornio/csi-snapshotter:v8.5.0-20260428,
      longhornio/csi-node-driver-registrar:v2.16.0-20260428,
      longhornio/livenessprobe:v2.18.0-20260428,
      longhornio/support-bundle-kit:v0.0.84
spec:
  releaseName: longhorn
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: helm-chart-longhorn
    namespace: longhorn-system
  values:
    defaultSettings:
      v1DataEngine: "true"
      upgradeChecker: "false"
      defaultDataPath: "/var/lib/longhorn"
    persistence:
      createStorageClass: true
      dataEngine: "v1"
      defaultClass: false
      defaultReplicaCount: 3
      defaultDataLocality: "best-effort"
      defaultFsType: "ext4"

    openshift:
      enabled: false
