---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: helm-chart-longhorn
    namespace: longhorn-system
  values:
    defaultSettings:
      v1DataEngine: "true"
      upgradeChecker: "false"
      defaultDataPath: "/var/lib/longhorn"
    persistence:
      createStorageClass: true
      dataEngine: "v1"
      defaultClass: true
      defaultReplicaCount: 3
      defaultDataLocality: "best-effort"
      defaultFsType: "ext4"
    openshift:
      enabled: false
