apiVersion: v1
kind: Secret
metadata:
  name: longhorn-r2-credentials
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Az9qrmGMRHFxM5UIsfk9txbEcjnTetxRRVMErX+f02U=,iv:9iMCv+fZ4riEZfjkt94h1X3MDF0fYrg6nh4ysWFQyIM=,tag:GOihsoXlsB5+xmY6GUn2lA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/Qbk23ibNTF+d/HYM9704XcCznT+/uX+uXTpAZy/4TZSfpCiI0kCU6nIDceRBhtQIQzWwrqBnvSzSCx0ViNufg==,iv:HiQEGBw/Ct7aU6Hm3DLlOBFeashybAVpYNEnJvmKTHw=,tag:5yu23L5icx0mCDTrCH7m7w==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:N1n1mTd5VyDtV/H2F1sp6lphn+BeU23jDhxJjc/xb36A9Uj45RjWZEQYF0xevlcKX2S1pIYoWcEhG0MGZ3uGuTc=,iv:MbHjk5Wwn/e/b3O+Q/U750W/SK973O4KAxwQZurwc4U=,tag:Trk4/vpohnD7VsZGcPge+g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVFg0QWxacWcrbnZ4a0xU
        M0VXaGxMU2pienJBdFY3Sk0xMURCbTh6amlNCisyNlVNK3JtaDFSSEFIWERSV1pz
        UzBMbmE4L1pWVkl3YUk3WFJOMUQ4VEkKLS0tIDd4YXlKVUprUllDSHpFTXhleU4z
        RzhVWS9PVERzbytYTURCUE9LQnZtTHMKuahRPz2KFTgU7OuW/7td0ArkcIf4iCsq
        M21fZQB3YNkSYTng7CEW2Sc22c6gdTNLRwf3JNLdg72X3Oft3e++FQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T14:31:19Z"
  mac: ENC[AES256_GCM,data:S9ARirB5mPt7YSLmP8w+ISVIqSyZWCRTBPIoxj2WEJvI8EmIVG0uUFCXF22CuTi2ZddRAaW9Dsvog7opGar2w9bWA9c2uHKTtOFMDHvncYd27tOorBhLOliG8BlUmXqrAbbhBHBJkplg2ZlHtJafcMp0d+//WMwYezqo+NpC9pE=,iv:JROc+SyuL+QVdTdQ/hVtM9iZYQyo4kkykJrEXKifDbY=,tag:LRXcgxc8U7zjY4FBY2I22g==,type:str]
  version: 3.13.1
