apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-vm
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fsType: ext4
  dataLocality: best-effort
  backupTargetName: r2-backup
  recurringJobSelector: '[{"name":"r2-backup","isGroup":true}]'
