apiVersion: application.logto.m.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: portainer-credential
  namespace: portainer
spec:
  managementPolicies:
  - Observe
  - Create
  - Update
  - LateInitialize
  forProvider:
    name: GitOps
    applicationIdRef:
      name: portainer
      policy:
        resolve: Always
  providerConfigRef:
    name: ccsn-logto
    kind: ClusterProviderConfig
  writeConnectionSecretToRef:
    name: portainer-oidc
---
apiVersion: application.logto.m.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: portainer-third-party-credential
  namespace: portainer
spec:
  managementPolicies:
  - Observe
  - Create
  - Update
  - LateInitialize
  forProvider:
    name: GitOps
    applicationIdRef:
      name: portainer-third-party
      policy:
        resolve: Always
  providerConfigRef:
    name: ccsn-logto
    kind: ClusterProviderConfig
  writeConnectionSecretToRef:
    name: portainer-third-party-oidc
