apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: external-anir
spec:
  exportTo: ["."]
  hosts:
    - anir.external-services.mesh.internal
  location: MESH_EXTERNAL
  ports:
    - number: 7789
      name: http-anir
      protocol: HTTP
  resolution: DNS
  endpoints:
    - address: openmediavault.local
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-anir
spec:
  parentRefs:
    - name: default-gateway
  hostnames:
    - anir.ccsn.dev
  rules:
    - backendRefs:
        - group: networking.istio.io
          kind: Hostname
          name: anir.external-services.mesh.internal
          port: 7789
