apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: external-autobangumi
spec:
  exportTo: ["."]
  hosts:
    - autobangumi.external-services.mesh.internal
  location: MESH_EXTERNAL
  ports:
    - number: 7899
      name: http-autobangumi
      protocol: HTTP
  resolution: DNS
  endpoints:
    - address: openmediavault.local
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-autobangumi
spec:
  parentRefs:
    - name: default-gateway
  hostnames:
    - ab.ccsn.dev
  rules:
    - backendRefs:
        - group: networking.istio.io
          kind: Hostname
          name: autobangumi.external-services.mesh.internal
          port: 7899
