apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./jellyfin.yaml
  - ./transmission.yaml
  - ./jackett.yaml
  - ./anir.yaml
  - ./radarr.yaml
  - ./sonarr.yaml
  - ./jellyseerr.yaml
  - ./bazarr.yaml
  - ./chinesesubfinder.yaml
  - ./jellystat.yaml
  - ./autobangumi.yaml
  - ./qbittorrent.yaml
