apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: external-transmission
spec:
  exportTo: ["."]
  hosts:
    - transmission.external-services.mesh.internal
  location: MESH_EXTERNAL
  ports:
    - number: 9091
      name: http-transmission
      protocol: HTTP
  resolution: DNS
  endpoints:
    - address: openmediavault.local
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-transmission
spec:
  parentRefs:
    - name: default-gateway
  hostnames:
    - transmission.ccsn.dev
  rules:
    - backendRefs:
        - group: networking.istio.io
          kind: Hostname
          name: transmission.external-services.mesh.internal
          port: 9091
