apiVersion: v1
kind: Secret
metadata:
  name: harbor-oidc
  namespace: harbor
type: Opaque
# This key is merged into Helm values via spec.valuesFrom.valuesKey.
# Keep configureUserSettings as a single-line JSON string value.
#   values.yaml: |
#     core:
#       configureUserSettings: '{"self_registration": false,"auth_mode": "oidc_auth","primary_auth_mode": true,"oidc_name": "ISNing","oidc_endpoint": "https://login.ccsn.dev/oidc","oidc_scope": "openid,profile,email,roles,offline_access","oidc_client_id": "534gp0torf1s2dsokwcwo","oidc_client_secret": "[REDACTED]","oidc_verify_cert": true,"oidc_auto_onboard": true,"oidc_user_claim": "username","oidc_groups_claim": "roles","oidc_group_filter": "^harbor:[a-z]+$","oidc_admin_group": "harbor:admin","oidc_logout": true}'
stringData:
  values.yaml: ENC[AES256_GCM,data:BingYfAGvr2LlR4rekErr6e9fdJRg5MYoL5KnKHGiZk9KExjXOAQALUtjTplB6KH7BhV5b9SUpiAJQtFvMnDHobFJbGSwTAadgr1YO1HR9qefgm+Xn0C1wYpvJkZ6O/0naYmCwBvKWQx+zsEZ5uZwQ1KVQMDdSnJWlGHAZlaq76MRt51e7Q/PlCSnw2qcTBrozl5X6wbh2WWwBqXxMYUrcCjWTM+F8Hmt8cIfRm+AWXkCaPXIBlTowkhYq/19R0bTnKvCpDK1UOC/Cu4N0fe9SxBNHfAityo3JWOS8VBENBDezY9hSfXWIpgifsl0yuQDOuEeSsAnvEq0fGqGoW2kFipfsAftCjvVf3XMH8zKKl7VLli2kOz4oKUBWevcXDwiGYWZdZE6jC0hCgt9lIdBLmtTxQoKqKmaZqGK9Z/UrrZ73lwmQTVX9Unk22yTXui+w3WLWPm+nlzF/VGWOV/RnLK3c8hFkXyYNANaAY8dyBb7RGWzR34fc+u7cgXHg6cj9J8VTQR1MyH2i/hTu5m86ymMa3TBWhUIOcWsCOJHVV46+o1vo0HBfnvF1DJm5Io1s7dVLrjOvYce+cuQGnElXRTDGQaJOIuecMY8/1KnhZUceKy/9wS9M2P+fjopZ1Skq5sjyMlniSViIGRexb65/oH296GY6rrgE8Gd0qsFLJi2jTDTu+az84=,iv:imxk/IZEwW38BqIQorKNP4zQtqgPP9Yxb7R4Rn14hOk=,tag:+S78XDxQpru/ur0qRTd6EQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WjVCWVJ4M3hTcGNkbnlP
        T2htVXlIeEZtUzRiakJTNG5uRUk5dEJ0ZmlFCk05SG9MVU5IeG1BSHJLNjBTQTVG
        VXUwaUIyY0Z1MGplVXpCWW5JUW1tS2sKLS0tIFo0Y3RVMUZGMVVKL0dGTFhaVUlx
        K2tJMVg1Q1Y2R3hqUWxCd1M2UENCN1kKtYfT9RJlFby26xJrh0MTT2rq9m14ywFF
        DtZ+3O2fNCMJflX6rsS6gQ/09rGspZN3KFZVGhJxMoY6jKwcgML6fQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T14:20:54Z"
  mac: ENC[AES256_GCM,data:gEtz0fWi1XMqBvIbE6J45BlTAJqjDsVssHMtVVJ8KXx1xNlM517wPHT7rL9Ab2H3s0MtmZEv35kdboC7x/g0+NQ5QS22JV+9qQAw8ICgVu1FgxV/unpQa4rvqqLk18vV/1GmSenAEYq67XYT6oRITLc9f1rw3DlfpapQW/g6Dvg=,iv:6wwGGDingZOeyOlbeDbhZWpccF6uxVHEHOtgttFsf/M=,tag:ELDwRIe/cn2EgldWaZ7nIw==,type:str]
  version: 3.13.1
