---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  releaseName: harbor
  interval: 30m
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      version: "1.*"
      interval: 12h
  values:
    existingSecretAdminPassword: harbor-admin-auth
    existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD

    expose:
      type: route
      route:
        hosts:
        - harbor.ccsn.dev
        parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: default-gateway
          namespace: prod
      tls:
        enabled: false
    externalURL: https://harbor.ccsn.dev

    # Route Harbor's outbound requests through the cluster egress proxy.
    proxy:
      httpProxy: http://proxy-svc.egress-system.svc.cluster.local:7890
      httpsProxy: http://proxy-svc.egress-system.svc.cluster.local:7890
      noProxy: 127.0.0.1,localhost,.svc,.cluster.local,harbor.harbor.svc,core,jobservice,registry,portal

    database:
      type: external
      external:
        host: harbor-pg-cluster-rw
        port: 5432
        username: app
        existingSecret: harbor-pg-cluster-app
        coreDatabase: registry
    redis:
      type: external
      external:
        addr: harbor-redis-master:6379
        username: default
        # Use an existing secret to connect to redis. The key must be REDIS_PASSWORD.
        existingSecret: harbor-redis-auth

    # Disable scanners to reduce footprint; can be enabled later.
    trivy:
      enabled: false

    persistence:
      enabled: true
      resourcePolicy: keep
      persistentVolumeClaim:
        registry:
          size: 100Gi
        jobservice:
          jobLog:
            size: 5Gi
        database:
          size: 10Gi
        redis:
          size: 5Gi

  valuesFrom:
    - kind: Secret
      name: harbor-oidc
      valuesKey: values.yaml

  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: ConfigMap
              name: harbor-core
              namespace: harbor
            patch: |
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: harbor-core
                namespace: harbor
              data:
                PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE: "ali-acr,aws-ecr,azure-acr,docker-hub,docker-registry,github-ghcr,google-gcr,harbor,huawei-SWR,jfrog-artifactory,tencent-tcr,volcengine-cr"
                REPLICATION_ADAPTER_WHITELIST: "ali-acr,aws-ecr,azure-acr,docker-hub,docker-registry,github-ghcr,google-gcr,harbor,huawei-SWR,jfrog-artifactory,tencent-tcr,volcengine-cr"
