kind: Secret
apiVersion: v1
metadata:
  name: grafana-credentials
stringData:
  client-id: ENC[AES256_GCM,data:swl97Z0=,iv:OHAN0tAAWNWMGJ8Rev7i8fqJb/nNGUNtQM3+g3fk9p4=,tag:qoWRp3WGFtsnIQ1KmTu4lQ==,type:str]
  client-secret: ENC[AES256_GCM,data:gVvAj4k=,iv:SftE384ED50tHIigY9ROrrfLp+oUUwqpHRSY+FFT/uQ=,tag:oUGheiumPedYJFoqzQLv+A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOTlhMDgrOFdrcFNzQW44
        dFpRd0ZSNkY4L3VLSnR5UVRDYTNlejVJT1FFCmVVdW9sZ0xKSXZIdXNGNDc3ay82
        cFMxOHNvVnJEWUp4YVlRZ0NCTWZXc2MKLS0tIElVUzQwbjRqSHd0NkRnYi9ZeUMx
        d0htc2NxZWxWQkVEN0U5dS84bmJVb2MK8KBDLupQyGguNg9f3e3kQsb2+GFqvr6q
        Y1ee5g1TldleBkRpq832wOHmB2ZRhjpZsFnnAjLyNDsHGdy/Mvcofg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T10:48:20Z"
  mac: ENC[AES256_GCM,data:PiI7l3VCFIbzGWOq1DUSqqfXSeOYEaDoMXWaChs4aJyAWXAjIgbS4YKntmmCIe7yTbnic2ZUQQg3OWRzJOweDoK4QkD1DAHAzSjSYzE5C498zkvwz9Jd2NtyZNCon1ySkc6t6f2DLrhU0/5ozJe+Ro9cZLKLLKBzv3/hO4JoMp8=,iv:9moPuqeA5rZYKqdqvjOfVYB6I0izU2z9HHqjK2dsk20=,tag:3zJA11Yb8EZWQiYHf3h9/A==,type:str]
  version: 3.13.1
