kind: Secret
apiVersion: v1
metadata:
  name: grafana-credentials
stringData:
  client-id: ENC[AES256_GCM,data:Kw13aPpNMY8qSZKkTTlqB0tLw8Km,iv:kWJC6UDOhqcadV269dXp/YCUwUfnoYPC5SrpLuo1A6I=,tag:FiiV2EjpcgYbf9ekYn1iNA==,type:str]
  client-secret: ENC[AES256_GCM,data:1kQrAPYhMGQsLT2IRG7YIvRKODqlYKL0kJ4Wuec4w5U=,iv:jRZAKkHh7Mhff5aCeSinq/Dn4RKTzH/gvPDb1ezI4d8=,tag:hzCP7tDDW/xgdMPnd16eoA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvME8vVlI0enlMeGFqcXdn
        YkdjTUNJWnp5ZVlQd0dONDlwS0Fpd1daUEVnCmpjdEc4S2FLUkNVUlcxdnNpWHRY
        dW1MZFFtdXhyRVhiMmxPS3h5VGRFUVUKLS0tIGhveHVrZDhzZkt3RnJXd2YvNFY3
        NmEvVCtaeW5LYkJhRmZ2aThiWktEVW8KClvMieRlxs8IDi7ozPr1j/T3ugoihqgZ
        jHrFpyy2RCF8ifF03gjjwZBkKVqYMNHd0865B2aOruYswzNkaZJipw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T07:11:44Z"
  mac: ENC[AES256_GCM,data:/EX8futk3K3WJigKWRd1ALTCV4xX+tEOkkAmJrYHZmnLJWffoCzSoTFmJw0G6G1rCAlQsHo65IT6ViTxc1uELS2/jRMHxVWIJZkl0Em0us8KprDhtV19Nw+HpQoHpHNF7Ohr1e9FiVyv4ahcJCTUCUz4wMlse6SwsGnMbFIHV2w=,iv:150SEplP5gQZpe3MMWS1Y9ticGFMl/HwkMgX99jPNgI=,tag:3toWVT2bkg5rXs2QYAK0DA==,type:str]
  version: 3.13.1
