apiVersion: v1
kind: Secret
metadata:
  name: harbor-oidc
  namespace: harbor
type: Opaque
# This key is merged into Helm values via spec.valuesFrom.valuesKey.
# Keep configureUserSettings as a single-line JSON string value.
#   values.yaml: |
#     core:
#       configureUserSettings: '{"self_registration": false,"auth_mode": "oidc_auth","primary_auth_mode": true,"oidc_name": "ISNing","oidc_endpoint": "https://login.ccsn.dev/oidc","oidc_scope": "openid,profile,email,roles,offline_access","oidc_client_id": "534gp0torf1s2dsokwcwo","oidc_client_secret": "[REDACTED]","oidc_verify_cert": true,"oidc_auto_onboard": true,"oidc_user_claim": "username","oidc_groups_claim": "roles","oidc_group_filter": "^harbor:[a-z]+$","oidc_admin_group": "harbor:admin","oidc_logout": true}'
stringData:
  values.yaml: ENC[AES256_GCM,data:am9w2jRIBkZXN29ypEEkGelaBTNnTl6ZOCJYu0BX83spcP98/WqQjhYqM6zO8G7ZsEsOexQiLAaQA1IaaZ+8FkeqfDQZLXduab9FTnYxpY9zXxRbTHzvf+PHjVSv8Rn0r3FjWs0dvSzeIpOWUaHwRYn9fTRnbJqs6uXoupfh+EJhTwBkWBni+MJ1QKRpM4jRkrxYY5uUQBiO3ZttSbya8M5XqeadvHD2lj6EanSUPfIrndXCsG0sjlDICXVSTWNyE8r8Y4xFKKxw7SLXyobH6ArQKJJPNhofMH54vB8jHH0MBgsYcTa8VE5sog5YBGkQSf9I7TP/qk+O377ypeNWDtIIwvofKF0l4xstX9UvCM+HhDBa7Vs/WCSj47gx4MQbV5/JN4kaBTmxJMt5GBk+0ga4TMI2aYGy7rlL3JixcR80RJvReoGRa6Q6tFQrc4RinHH3dr4NAFOjVhl0alY3xTR3O/QQQLQbnPKk23sHezA88kcerRAW7FXBwEFXQDpSOiXssW8Wl6RS4AJS3zO/w18OFF1jVCFa4nS3RBBOL2eX/dXyrMdnVebFQrTsyvjZGwFHYseVnzWxrwe/srS8jlv+6e04bSoNhoncONPj2yQwG6+GvlH7DVJ76JWe92rDEkfRLtSkYn1M7dthI0f0i2had+4z8li3IIy/14VGPcga2+EdbF69aORApILgyqOXcxxgipQzy4Tf+nZEQRD6X3M=,iv:Z5Mn/ROB5jDdoUIXgIivwUs+9a5qzhK2qpwP6RFsToE=,tag:s+V1jqHP1bBCNvPBA2fUEg==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bk1ubVQ3RU9xbVQ1ajJV
        Qkl4UkVnamJicFI5S0Nqa0NibDJUZ2dWdEdzCmRSdUIvTWJwbEVIeldERDdDT3I0
        SFBKNmtmUFpaVWJtRGNjdVZrWHpDSjQKLS0tIEhoQmNHU2tHTzgxRVdjNVVPQnBw
        TzJOc01DQ3FYVTFqMGpIdEFTUXlqd2MKmaKZAsUiRTNei5TbYvH0l4STXXZDt2vi
        dcXlAJJwVR4Plju+32/R0aMew6aKjoTil5jMXskak4IyM8B7x7jJsg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T08:22:31Z"
  mac: ENC[AES256_GCM,data:CERoLtzUMjTqEe3mJd1Gi+Zg3E0RjYLg5bhvxe76WUaUOHBwo41wdm5NrP3GdVcHeRuDthiqsKnlXiCyxamEVLNIFNGk1eYfIjBbovcoDEzOJVqTqoe2O1jUS53IRz52PBHeak8M5JAUL19mLyAfo9x4pz/nvUEwk7/b9oVDpsY=,iv:31pnd9L9V/oODiJYtMSCgUj1gw7DyAIMd8aIUCkyUYs=,tag:tJTVpsiDrQTDXK6+taHdLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
