---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:

  # Why isn't this HA?
  # Vaultwarden isn't designed for HA.
  # Although there's some workaround to run multiple instances, we'd rather endure
  # short downtime during redeploy than risk data loss or corruption.
  # See also: https://github.com/dani-garcia/vaultwarden/discussions/2691

  # The pg database supports HA, so we enable it for shorter downtime in case one of pg instances goes down.

  releaseName: vaultwarden
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: helm-chart-vaultwarden
    namespace: prod
  values:
    # HTTPS required for Passkey support
    domain: 'https://vault.ccsn.dev'

    vaultwarden:
      signupsAllowed: false
      signupsVerify: true
      invitationsAllowed: true
      sendsAllowed: true
      passwordIterations: 600000
      proxy:
        ipHeader: X-Envoy-External-Address

    admin:
      existingSecret: vaultwarden-admin
      existingSecretTokenKey: admin-token

    smtp:
      enabled: true
      host: smtp.office365.com
      port: 587
      from: noreply@ccsn.dev
      fromName: Vaultwarden
      security: starttls
      username: noreply@ccsn.dev
      existingSecret: vaultwarden-smtp
      existingSecretPasswordKey: password

    database:
      mode: external
      external:
        vendor: postgres
        existingSecret: vaultwarden-pg-cluster-app
        existingSecretUrlKey: uri

    extraEnv:
      - name: PUSH_ENABLED
        value: "true"
      - name: PUSH_INSTALLATION_ID
        valueFrom:
          secretKeyRef:
            name: vaultwarden-push
            key: PUSH_INSTALLATION_ID
      - name: PUSH_INSTALLATION_KEY
        valueFrom:
          secretKeyRef:
            name: vaultwarden-push
            key: PUSH_INSTALLATION_KEY
      - name: SSO_ENABLED
        value: "true"
      - name: SSO_SIGNUPS_MATCH_EMAIL # On SSO Signup if a user with a matching email already exists make the association (default true)
        value: "true"
      - name: SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION # Allow unknown email verification status (default false). Allowing this with SSO_SIGNUPS_MATCH_EMAIL open potential account takeover.
        value: "false"
      - name: SSO_AUTHORITY
        value: "https://login.ccsn.dev/oidc"
      - name: SSO_SCOPES
        value: "openid email profile offline_access"
      - name: SSO_CLIENT_ID
        value: "1a2zc0uue83n20iy87u5a"
      - name: SSO_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: vaultwarden-oidc
            key: SSO_CLIENT_SECRET

    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 200m

    data:
      persistence:
        enabled: true
        size: 5Gi
