---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-oci-repo.yaml
  - pg-cluster.yaml
  - objectstore.yaml
  - scheduled-backup.yaml
  - helm-release.yaml
  - secrets.yaml
  - httproute.yaml
