apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vaultwarden-pg-backup
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: cluster
  cluster:
    name: vaultwarden-pg-cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
