# Vaultwarden Admin Token Secret
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-admin
type: Opaque
stringData:
  admin-token: ENC[AES256_GCM,data:HpQ2tew+ZcGZU0exCSHD2g==,iv:fcmwimbpXXw+jUwoWQsLGbpbBgoAEgyRCr2r08YkCJA=,tag:kHgvQh8h23TTi78UHoethA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUVdNVXdkRXN1NHl3Q1RZ
        MmFobmM1VlAxSHhua2loblpBQ0Qvc1I3dUdnCmxrU09VRVFPVGx4amVMblI3dFN2
        Z3hwM0gzR0ZvdFdmSmt1T2ZmOG12bG8KLS0tIHdHRTM4WUh4V0hzdDAwK2dWdlMv
        V3pvc1VaUEdhdUVQMXoveWpuM1E3T2cKAYNyq4QrlcJDc+95DalfdXj7VCPFrHd4
        1wBSU/WkNoCll1rqDxCjVibrekUtG7QgRjeCv/TH4IRyORmC2g06lw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T13:01:27Z"
  mac: ENC[AES256_GCM,data:psp5ur9lpBsodoSjAnNL9tMRvPgJx94/DrhvIOmjSW7Ec/9PFrsIIjsciHEOBDZ/2C2hAXYyma45BBqsNTqDlXUligLI6P9xQlkJIsEm3iEg5o+ne3Fej0tkDYjWaG/yadZj/slvYUb+GGyXp8jdW+Zuqdo/VYc5uG3wFM8jAlw=,iv:mhYqZ8r4dIHeVLgfsdiG5l5/emRLSXA9Ip1HGXbAR1U=,tag:NEWVE6DES1HIWuaxaM6l9g==,type:str]
  version: 3.13.3
---
# Vaultwarden SMTP Credentials
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-smtp
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:0+x+1/aKVlU=,iv:utKU9fs/1l+MvAILmmkSHguNJ1sUlz5uz3Rs8J5yQSo=,tag:HcHE/hs8AyjweHNnLs0a9w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUVdNVXdkRXN1NHl3Q1RZ
        MmFobmM1VlAxSHhua2loblpBQ0Qvc1I3dUdnCmxrU09VRVFPVGx4amVMblI3dFN2
        Z3hwM0gzR0ZvdFdmSmt1T2ZmOG12bG8KLS0tIHdHRTM4WUh4V0hzdDAwK2dWdlMv
        V3pvc1VaUEdhdUVQMXoveWpuM1E3T2cKAYNyq4QrlcJDc+95DalfdXj7VCPFrHd4
        1wBSU/WkNoCll1rqDxCjVibrekUtG7QgRjeCv/TH4IRyORmC2g06lw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T13:01:27Z"
  mac: ENC[AES256_GCM,data:psp5ur9lpBsodoSjAnNL9tMRvPgJx94/DrhvIOmjSW7Ec/9PFrsIIjsciHEOBDZ/2C2hAXYyma45BBqsNTqDlXUligLI6P9xQlkJIsEm3iEg5o+ne3Fej0tkDYjWaG/yadZj/slvYUb+GGyXp8jdW+Zuqdo/VYc5uG3wFM8jAlw=,iv:mhYqZ8r4dIHeVLgfsdiG5l5/emRLSXA9Ip1HGXbAR1U=,tag:NEWVE6DES1HIWuaxaM6l9g==,type:str]
  version: 3.13.3
---
# Vaultwarden R2 Backup Credentials
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-r2-credentials
type: Opaque
stringData:
  access-key: ENC[AES256_GCM,data:hezB7vLCQirWbb69l/Jw5NBCupCBo3BHX4yBtFwPNgA=,iv:LYol5WW+XLbdEvdKF9q2946yDuMjsaeL0b5nHSZmIRQ=,tag:I9HVxuGC0UZfGO4Rg7qchw==,type:str]
  secret-key: ENC[AES256_GCM,data:MGUni7nxoqmtagGF35d93CL8g+/IWhEFmse2eSyDWMQY2Xuz4eSqWRHt+j3Ldphk3tOmTxmaUu1uA1P98If5RA==,iv:XaGA7PoyZlSWygIaG0l4HHR/1XsN+ddBCLAXuMjTYtU=,tag:HJvdUnGFwIvdF89GnsaBqA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUVdNVXdkRXN1NHl3Q1RZ
        MmFobmM1VlAxSHhua2loblpBQ0Qvc1I3dUdnCmxrU09VRVFPVGx4amVMblI3dFN2
        Z3hwM0gzR0ZvdFdmSmt1T2ZmOG12bG8KLS0tIHdHRTM4WUh4V0hzdDAwK2dWdlMv
        V3pvc1VaUEdhdUVQMXoveWpuM1E3T2cKAYNyq4QrlcJDc+95DalfdXj7VCPFrHd4
        1wBSU/WkNoCll1rqDxCjVibrekUtG7QgRjeCv/TH4IRyORmC2g06lw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T13:01:27Z"
  mac: ENC[AES256_GCM,data:psp5ur9lpBsodoSjAnNL9tMRvPgJx94/DrhvIOmjSW7Ec/9PFrsIIjsciHEOBDZ/2C2hAXYyma45BBqsNTqDlXUligLI6P9xQlkJIsEm3iEg5o+ne3Fej0tkDYjWaG/yadZj/slvYUb+GGyXp8jdW+Zuqdo/VYc5uG3wFM8jAlw=,iv:mhYqZ8r4dIHeVLgfsdiG5l5/emRLSXA9Ip1HGXbAR1U=,tag:NEWVE6DES1HIWuaxaM6l9g==,type:str]
  version: 3.13.3
---
# Vaultwarden Push Credentials
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-push
type: Opaque
stringData:
  PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:xrmvq8dEI+qW6DQy6aOHAcNA6Nrci4GLlbWV4MK4ifd5Wgrc,iv:XTpN52b+LabKgYzWTLbcAFb+4kgNq+WtYIR3VqUSO9E=,tag:Jt+78EbKSwd4BN4omm17iA==,type:str]
  PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:eKjTbQfVIx5KL8jTmVpzjJwhDtQ=,iv:3pWMJ3QlkC/tSfh3PGufq43dNtgw5/6TQVnl86aMbAs=,tag:dj1piRA3QLNM/ojLP8Ibnw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUVdNVXdkRXN1NHl3Q1RZ
        MmFobmM1VlAxSHhua2loblpBQ0Qvc1I3dUdnCmxrU09VRVFPVGx4amVMblI3dFN2
        Z3hwM0gzR0ZvdFdmSmt1T2ZmOG12bG8KLS0tIHdHRTM4WUh4V0hzdDAwK2dWdlMv
        V3pvc1VaUEdhdUVQMXoveWpuM1E3T2cKAYNyq4QrlcJDc+95DalfdXj7VCPFrHd4
        1wBSU/WkNoCll1rqDxCjVibrekUtG7QgRjeCv/TH4IRyORmC2g06lw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T13:01:27Z"
  mac: ENC[AES256_GCM,data:psp5ur9lpBsodoSjAnNL9tMRvPgJx94/DrhvIOmjSW7Ec/9PFrsIIjsciHEOBDZ/2C2hAXYyma45BBqsNTqDlXUligLI6P9xQlkJIsEm3iEg5o+ne3Fej0tkDYjWaG/yadZj/slvYUb+GGyXp8jdW+Zuqdo/VYc5uG3wFM8jAlw=,iv:mhYqZ8r4dIHeVLgfsdiG5l5/emRLSXA9Ip1HGXbAR1U=,tag:NEWVE6DES1HIWuaxaM6l9g==,type:str]
  version: 3.13.3
