# Vaultwarden Admin Token Secret
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-admin
type: Opaque
stringData:
  admin-token: ENC[AES256_GCM,data:FX8qrq9ZFQFpvvMhBmQ7SQ==,iv:T6wo3VvjSameSnLa380HY3PoE4sENqSoSlb1SQw3H4g=,tag:p9K7nOyzTXSMwiHzNUpzUw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Yk1IeFpoYmtOaUF6NUll
        Z3lJQzBLYjVmRWYrdllrbXFRY1dWaWpIU1VjCjJQWkdYUS9ZcHAvOHlmZDFESDBl
        S1A0V05rVjdKT1NvSDZrd1h0dFpFMjgKLS0tIHJDVHZIZWRpMlYyOWVIUVFzNkZl
        UVl1YjJTWCtEb0h0YVJBUDBGejdIZzQK/0zCbb2iltS0EUekVzUlpaPMT3eqVOwY
        ewdHpT/6Zw6j5M/bHaCEGNUdA3khEicq+xIc47nNSphMLaJ4oDLv3A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T12:01:20Z"
  mac: ENC[AES256_GCM,data:DoR2jTPqxtj8fimC/Rl/v7ZRPUg6Q7+V7fBPax9PmoPCT9CTw95ndGw4Vq18Oz+RCccoZRhxNHRN5QmEehoXv9JpfbX53QAuK/el1Aq2aTpalxjFr09pmKom0yfttcx9VFsF4sx/5n0kdve+A018oifJwASdbxhSw9OZnjvZAjM=,iv:ZB/PunIr+dQVijjSr179Sa9BreeLcdM/Kg301+Ohxoc=,tag:HenNih/cVmVoTzDd8pw8QQ==,type:str]
  version: 3.13.1
---
# Vaultwarden SMTP Credentials
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-smtp
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:NmpQ6jtjZ/o=,iv:3uO1Jv5tvZt25NJO7hw+lUTFSbUryC50/JqrdIunK5M=,tag:X2v/cbhg1Lkx+Prf9BIi2g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Yk1IeFpoYmtOaUF6NUll
        Z3lJQzBLYjVmRWYrdllrbXFRY1dWaWpIU1VjCjJQWkdYUS9ZcHAvOHlmZDFESDBl
        S1A0V05rVjdKT1NvSDZrd1h0dFpFMjgKLS0tIHJDVHZIZWRpMlYyOWVIUVFzNkZl
        UVl1YjJTWCtEb0h0YVJBUDBGejdIZzQK/0zCbb2iltS0EUekVzUlpaPMT3eqVOwY
        ewdHpT/6Zw6j5M/bHaCEGNUdA3khEicq+xIc47nNSphMLaJ4oDLv3A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T12:01:20Z"
  mac: ENC[AES256_GCM,data:DoR2jTPqxtj8fimC/Rl/v7ZRPUg6Q7+V7fBPax9PmoPCT9CTw95ndGw4Vq18Oz+RCccoZRhxNHRN5QmEehoXv9JpfbX53QAuK/el1Aq2aTpalxjFr09pmKom0yfttcx9VFsF4sx/5n0kdve+A018oifJwASdbxhSw9OZnjvZAjM=,iv:ZB/PunIr+dQVijjSr179Sa9BreeLcdM/Kg301+Ohxoc=,tag:HenNih/cVmVoTzDd8pw8QQ==,type:str]
  version: 3.13.1
---
# Vaultwarden R2 Backup Credentials
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-r2-credentials
type: Opaque
stringData:
  access-key: ENC[AES256_GCM,data:JKkivJR1Zac/nTz5mTqWvFdEWxwN2AMIvN6e1ez1KhY=,iv:r6E5jWFsSXhNyD0AGjnZf97wD83wGbHK81YHwLuKLXA=,tag:aTPwtgF7WnI2N3/407tyJA==,type:str]
  secret-key: ENC[AES256_GCM,data:k6ByZ5GHsnXVmJDguQgeZv0RYaRUuR3UU7pOnp5SyhbSBZjWZEoG5w41LgU7FsxqXIy3QJgoJe5L64aocCNycQ==,iv:jyKcm98sD5tqUerjivOHRR+K2u4Ysl9qN73bCepj+gA=,tag:UARkc/7LR3YtFEBNdCiHAQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Yk1IeFpoYmtOaUF6NUll
        Z3lJQzBLYjVmRWYrdllrbXFRY1dWaWpIU1VjCjJQWkdYUS9ZcHAvOHlmZDFESDBl
        S1A0V05rVjdKT1NvSDZrd1h0dFpFMjgKLS0tIHJDVHZIZWRpMlYyOWVIUVFzNkZl
        UVl1YjJTWCtEb0h0YVJBUDBGejdIZzQK/0zCbb2iltS0EUekVzUlpaPMT3eqVOwY
        ewdHpT/6Zw6j5M/bHaCEGNUdA3khEicq+xIc47nNSphMLaJ4oDLv3A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T12:01:20Z"
  mac: ENC[AES256_GCM,data:DoR2jTPqxtj8fimC/Rl/v7ZRPUg6Q7+V7fBPax9PmoPCT9CTw95ndGw4Vq18Oz+RCccoZRhxNHRN5QmEehoXv9JpfbX53QAuK/el1Aq2aTpalxjFr09pmKom0yfttcx9VFsF4sx/5n0kdve+A018oifJwASdbxhSw9OZnjvZAjM=,iv:ZB/PunIr+dQVijjSr179Sa9BreeLcdM/Kg301+Ohxoc=,tag:HenNih/cVmVoTzDd8pw8QQ==,type:str]
  version: 3.13.1
---
# Vaultwarden Push Credentials
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-push
type: Opaque
stringData:
  PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:ns9DFjgZkgLDEk6F+Wx2ebB6tPCFzgQqBzJOzQWiJilM8Obu,iv:aD87WiuZUEtxNoCn/ItYO7vvA5a6bXiC0/zuI1q7pF8=,tag:vxINqui5ck0NUi3qy8UyNw==,type:str]
  PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:aIpTm/XD0Sbs1nZ8aPaS3mV9JkU=,iv:e2xs0y+ilH5GchPauWM/nnbypBNbywiZ9oOKjrKoZtM=,tag:9FHP2H5l5JuJtvAAfFVWEA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Yk1IeFpoYmtOaUF6NUll
        Z3lJQzBLYjVmRWYrdllrbXFRY1dWaWpIU1VjCjJQWkdYUS9ZcHAvOHlmZDFESDBl
        S1A0V05rVjdKT1NvSDZrd1h0dFpFMjgKLS0tIHJDVHZIZWRpMlYyOWVIUVFzNkZl
        UVl1YjJTWCtEb0h0YVJBUDBGejdIZzQK/0zCbb2iltS0EUekVzUlpaPMT3eqVOwY
        ewdHpT/6Zw6j5M/bHaCEGNUdA3khEicq+xIc47nNSphMLaJ4oDLv3A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T12:01:20Z"
  mac: ENC[AES256_GCM,data:DoR2jTPqxtj8fimC/Rl/v7ZRPUg6Q7+V7fBPax9PmoPCT9CTw95ndGw4Vq18Oz+RCccoZRhxNHRN5QmEehoXv9JpfbX53QAuK/el1Aq2aTpalxjFr09pmKom0yfttcx9VFsF4sx/5n0kdve+A018oifJwASdbxhSw9OZnjvZAjM=,iv:ZB/PunIr+dQVijjSr179Sa9BreeLcdM/Kg301+Ohxoc=,tag:HenNih/cVmVoTzDd8pw8QQ==,type:str]
  version: 3.13.1
---
# Vaultwarden SSO Credentials
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-oidc
type: Opaque
stringData:
  SSO_CLIENT_SECRET: ENC[AES256_GCM,data:MGxp7fU=,iv:DAxdJuZhk0B7zQ3igRrn73NVTckdmNLSiwPjR29Dx6M=,tag:GZNu7vS1K6hH6/5a0nuAqg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Yk1IeFpoYmtOaUF6NUll
        Z3lJQzBLYjVmRWYrdllrbXFRY1dWaWpIU1VjCjJQWkdYUS9ZcHAvOHlmZDFESDBl
        S1A0V05rVjdKT1NvSDZrd1h0dFpFMjgKLS0tIHJDVHZIZWRpMlYyOWVIUVFzNkZl
        UVl1YjJTWCtEb0h0YVJBUDBGejdIZzQK/0zCbb2iltS0EUekVzUlpaPMT3eqVOwY
        ewdHpT/6Zw6j5M/bHaCEGNUdA3khEicq+xIc47nNSphMLaJ4oDLv3A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T12:01:20Z"
  mac: ENC[AES256_GCM,data:DoR2jTPqxtj8fimC/Rl/v7ZRPUg6Q7+V7fBPax9PmoPCT9CTw95ndGw4Vq18Oz+RCccoZRhxNHRN5QmEehoXv9JpfbX53QAuK/el1Aq2aTpalxjFr09pmKom0yfttcx9VFsF4sx/5n0kdve+A018oifJwASdbxhSw9OZnjvZAjM=,iv:ZB/PunIr+dQVijjSr179Sa9BreeLcdM/Kg301+Ohxoc=,tag:HenNih/cVmVoTzDd8pw8QQ==,type:str]
  version: 3.13.1
