apiVersion: v1
kind: ConfigMap
metadata:
  name: seaweedfs-s3-direct-dns
  namespace: external-dns-system
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
data:
  s3.server: |
    s3.ccsn.dev:1053 s3.319.ccsn.dev:1053 {
        template IN A {
            match ^s3\.(319\.)?ccsn\.dev\.$
            answer "{{ .Name }} 60 IN A 192.168.1.86"
            fallthrough
        }
        template IN AAAA {
            match ^s3\.(319\.)?ccsn\.dev\.$
            rcode NOERROR
            fallthrough
        }
        template IN HTTPS {
            match ^s3\.(319\.)?ccsn\.dev\.$
            rcode NOERROR
            fallthrough
        }
        template IN SVCB {
            match ^s3\.(319\.)?ccsn\.dev\.$
            rcode NOERROR
            fallthrough
        }
        forward . 1.1.1.1 8.8.8.8
        cache 60
        errors
    }
