apiVersion: application.logto.m.crossplane.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  managementPolicies:
  - Observe
  - Create
  - Update
  - LateInitialize
  forProvider:
    name: Kubernetes Cluster-wide Gateway
    type: Traditional
    description: ''
    isThirdParty: false
    redirectUris:
    - https://oauth2-gateway.ccsn.dev/oauth2/callback
    postLogoutRedirectUris: []
    corsAllowedOrigins: []
    oidcClientMetadataExtra: '{"backchannelLogoutSessionRequired":false}'
    customClientMetadataExtra: '{"idTokenTtl":3600,"refreshTokenTtlInDays":14,"alwaysIssueRefreshToken":false,"rotateRefreshToken":true,"allowTokenExchange":false}'
  providerConfigRef:
    name: ccsn-logto
    kind: ClusterProviderConfig
