apiVersion: application.logto.m.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: oauth2-proxy-credential
  namespace: oauth2-proxy
spec:
  managementPolicies:
  - Observe
  - Create
  - Update
  - LateInitialize
  forProvider:
    name: GitOps
    applicationIdRef:
      name: oauth2-proxy
      policy:
        resolve: Always
  providerConfigRef:
    name: ccsn-logto
    kind: ClusterProviderConfig
  writeConnectionSecretToRef:
    name: oauth2-proxy-oidc
