apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: external-base
spec:
  exportTo: ["."]
  hosts:
    - base.external-services.mesh.internal
  location: MESH_EXTERNAL
  ports:
    - number: 5246
      name: http-base
      protocol: HTTP
  resolution: DNS
  endpoints:
    - address: openmediavault.local
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-base
spec:
  parentRefs:
    - name: default-gateway
  hostnames:
    - base.ccsn.dev
  rules:
    - matches:
        - path:
            type: RegularExpression
            value: "^/(p|api|assets|d).*"
      timeouts:
        request: 0s
      backendRefs:
        - group: networking.istio.io
          kind: Hostname
          name: base.external-services.mesh.internal
          port: 5246
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: base.snc.moe
            port: 443
            statusCode: 302
