apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./media/
  - ./admin/
  - ./network/
  - ./alist.yaml
  - ./flare.yaml
  - ./share.yaml
  - ./cam.yaml
  - ./wiki.yaml
  - ./uptime-kuma.yaml
  - ./base.yaml
  - ./home-assistant.yaml
