apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: external-share
spec:
  exportTo: ["."]
  hosts:
    - share.external-services.mesh.internal
  location: MESH_EXTERNAL
  ports:
    - number: 5245
      name: http-share
      protocol: HTTP
  resolution: DNS
  endpoints:
    - address: openmediavault.local
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-share
spec:
  parentRefs:
    - name: default-gateway
  hostnames:
    - share.ccsn.dev
  rules:
    - timeouts:
        request: 0s
      backendRefs:
        - group: networking.istio.io
          kind: Hostname
          name: share.external-services.mesh.internal
          port: 5245
