---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  releaseName: tofu-controller
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: tofu-controller
    namespace: flux-system
  install:
    crds: Create
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    runner:
      image:
        repository: ghcr.io/the-ccsn/k8s-gitops/tf-runner
        tag: v0.16.3-custom-202605251544@sha256:8600a5292bb1773b55486e093289258f2dc3f16112856a11f8a523f018472d28
      serviceAccount:
        allowedNamespaces:
          - flux-system
          - harbor
