kind: will-be-ignored
metadata:
  name: will-be-ignored
spec:
  values:
    vmagent:
      spec:
        scrapeInterval: 20s
        externalLabels:
          # For multi-cluster setups it is useful to use "cluster" label to identify the metrics source.
          cluster: kubevirt-cluster-319
          env: kubevirt
      ingress:
        hosts:
          - kubevirt-vmagent.ccsn.dev
