apiVersion: application.logto.m.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: harbor-credential
  namespace: harbor
spec:
  managementPolicies:
  - Observe
  - Create
  - Update
  - LateInitialize
  forProvider:
    name: GitOps
    applicationIdRef:
      name: harbor
      policy:
        resolve: Always
  providerConfigRef:
    name: ccsn-logto
    kind: ClusterProviderConfig
  writeConnectionSecretToRef:
    name: harbor-oidc
