---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./nodes-cache-pvc.yaml
  - ./sub-converter-script-config.yaml
  - ./sub-converter-suburls-secret.yaml
  - ./singbox-main.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
  - ./authz-policy.yaml
  - ./work-cache-pvc.yaml
  - ./restarter
