---
apiVersion: v1
kind: Service
metadata:
  name: proxy-svc
  namespace: egress-system
  labels:
    app: proxy-engine
spec:
  trafficDistribution: PreferSameNode
  ports:
  - port: 7890
    name: mixed-proxy
    appProtocol: tcp # Avoid sniffing this as HTTP by Istio, which causes 404
    protocol: TCP
    targetPort: 7890
  - port: 8891
    name: public-http
    appProtocol: tcp # The client speaks HTTP proxy; Istio must not intercept CONNECT.
    protocol: TCP
    targetPort: 8891
  - port: 8892
    name: public-v4
    appProtocol: tcp
    protocol: TCP
    targetPort: 8892
  - port: 8893
    name: public-v6
    appProtocol: tcp
    protocol: TCP
    targetPort: 8893
  - port: 8894
    name: campus-http
    appProtocol: tcp
    protocol: TCP
    targetPort: 8894
  - port: 8895
    name: campus-v4
    appProtocol: tcp
    protocol: TCP
    targetPort: 8895
  - port: 8896
    name: campus-v6
    appProtocol: tcp
    protocol: TCP
    targetPort: 8896
  selector:
    app: proxy-engine
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-engine-headless
  namespace: egress-system
  labels:
    istio.io/use-waypoint: none
spec:
  clusterIP: None
  ports:
    - port: 9090
      name: http-clash-api
      appProtocol: http
      targetPort: clash-api
  selector:
    app: proxy-engine
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-dashboard
  namespace: egress-system
spec:
  trafficDistribution: PreferSameNode
  ports:
    - port: 8080
      name: http-webui
      appProtocol: http
      targetPort: http-webui
  selector:
    app: proxy-dashboard
