apiVersion: v1
kind: Secret
metadata:
  name: sub-converter-suburls-secret
  namespace: egress-system
# Separate multiple sub-URLs with comma, and each sub-URL is in the format of "name:url"
# Optional: set NODE_SELECTIONS like
#   HongKong = [ 'HongKong URLTest', '[YZT] 香港1', '[YZT] 香港2' ]
#   UnitedStates = [ 'UnitedStates URLTest', 'My US Node' ]
stringData:
  SUB_URLS: ENC[AES256_GCM,data:1xGrnWKTozkkDt5rUd900pvr41GlifVpa15VrfyX/miVySe5uH6iPx8uSyFma7j3gSzD8hvsrinmq58llTiHpOsKL9+0/eUx8jtf9WYkEImLbAf0KaMNqZ+pwgEgDZZyulYt82xeCG9+8eUUAzzllcvV6yuq4XMLIp4ciqI4cCLnDaz/RqY3qVDgSpAOU9t/kLfqD0m4uGc2Ag+WA3SP7zZamzNR0utNpOzRLO1TdtXRSPN8KfmYmWdEjmJjZgyvt+WmKq7a+MjTOfX8oPDnZ1zsjCW0Qe4laAV5JfuEEmdYrQubCaDdu5qs6cWecNNRfpxglkGOK2vuY7bN2Mpxu0z4TiImiDYljWwvW8WGzIxarVIWLpwInAvuVM6W2mqNBkGWFG0=,iv:vUFEBBn2c7dn8DMIoaOmm2ya9lIS0q52CA5gftH7Ezk=,tag:OBChUaq7gkY6jdtuySfXRQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUi90all4dk9pRjlxU2NR
        MTJOS1ZSVWlaVmVUUEgyeERqaHhsMVRIeG5jCjhqbFJlbHdsS2JRYmcxVTVLZm1Q
        cDA2dlBsVTZ3dnJITlNlWVFvdGczMVEKLS0tIG45QUJmeW00czRtZ2kwdE12dGV5
        VDhZR0FtOWZBTklrczR1RW1ldmY2cjgK5BJuywxJvL3e+HcE1xQkvwSeVTfmTHWj
        hTxWnaOJ02YENtIrKzUGf+ySn9yGD268Z2K1gJ0Glc5FfK/+41IZmg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T07:54:36Z"
  mac: ENC[AES256_GCM,data:eruCiHypODHVZ/Ba6nB6UR0tzew/i62Sp463T+9rUIDP0V5ydmq8G+55UBXw0vnpvCTOJ/0jq7oTr4huji21tnbP3n4Euw6q0zcck5AINfbTacgFC0L9pyQsD+S8xDx4wj0a2IgxyurOcqCYljfTdcI/TorYfLJT0bPkOd9eIqo=,iv:Nf8yfxx5EQFAubvlvI+s1lBGfv+Cx7gM6DiI/rsZ2BQ=,tag:hMD9aAq19Rqg7O0FtM7lXA==,type:str]
  version: 3.13.1
