apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pve.yaml
  - ./omv.yaml
  - ./omv-netdata.yaml
  - ./pve-netdata.yaml
  - ./admin-dl380.yaml
  - ./admin-t410.yaml
  - ./admin-dl160.yaml
  - ./admin-r730.yaml
  - ./portainer.yaml
  - ./fail2ban.yaml
  - ./admin-dl380-compat.yaml
  - ./admin-t410-compat.yaml
