# https://github.com/cilium/cilium/tree/v1.19.0/install/kubernetes/cilium
enableIPv4Masquerade: true

# ======================== Tuning Cilium ========================
# https://docs.cilium.io/en/stable/operations/performance/tuning/
# https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/
kubeProxyReplacement: true

k8s:
  # https://github.com/cilium/cilium/pull/37601
  apiServerURLs: https://192.168.1.163:6443

devices: ovsbr+

bpf:
  # Use l2 insead l3 for KubeVirt compatability https://github.com/cilium/cilium/issues/37265#issuecomment-2626483413
  datapathMode: netkit-l2
  # Disable for Istio compatability
  masquerade: false
  distributedLRU:
    enabled: true
  mapDynamicSizeRatio: 0.08

routingMode: native
autoDirectNodeRoutes: true

# TODO: Add services CIDR after Cilium supports multiple CIDRs: https://github.com/cilium/cilium/issues/21945
ipv4NativeRoutingCIDR: 172.16.0.0/16
ipv6NativeRoutingCIDR: fdfd:cafe:00:0001::/64

bandwidthManager:
  enabled: true
  bbr: true

loadBalancer:
  mode: dsr
  acceleration: best-effort # XDP acceleration

bpfClockProbe: true

# ======================== Work with Istio ========================
# https://docs.cilium.io/en/latest/network/servicemesh/istio/
cni:
  exclusive: false
socketLB:
  hostNamespaceOnly: true
# disable L7 Proxy
l7Proxy: false

# ============================  Dual Stack  ============================
ipv6:
  enabled: true
# -- Enables masquerading of IPv6 traffic leaving the node from endpoints.
enableIPv6Masquerade: true

# ============================  L2 Announcements  ============================
# https://docs.cilium.io/en/stable/network/l2-announcements/
l2announcements:
  enabled: true
k8sClientRateLimit:
  qps: 100
  burst: 200

# ============================  BGP Control Plane  ============================
# https://docs.cilium.io/en/stable/network/bgp-control-plane/
bgpControlPlane:
  enabled: true

operator:
  replicas: 1 # For now that I have only 1 node

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true