kind: will-be-ignored
metadata:
  name: will-be-ignored
spec:
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false" # Disable Cloudflare proxy for this service
      # MUST be patched
      external-dns.alpha.kubernetes.io/hostname: "kubevirt-cluster-319.ingress.internal.ccsn.dev" # Set the desired hostnames for External DNS
  listeners:
    - name: http
      protocol: HTTP
      port: 8080
      hostname: "*.kubevirt-cluster-319.ccsn.dev"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Selector
          selector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: NotIn
                values:
                  - prod
                  - staging
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.kubevirt-cluster-319.ccsn.dev"
      tls:
        mode: Terminate
        certificateRefs:
          - name: infra-gateway-wildcard-isning-moe-tls
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Selector
          selector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: NotIn
                values:
                  - prod
                  - staging
