---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/apiserver-oidc/
  - ../../base/cert-manager/
  - ../../base/kubevirt/
  - ../../base/gateway/
  - ../../base/harbor/
  - ../../base/kiali/
  - ../../base/flux/
  - ../../base/cloudnative-pg/
  - ../../base/victoria-metrics/
  - ../../base/egress/
  - ./cloudflare-operator/
  - ./319-reroute/

patches:
  - target:
      kind: Gateway
      name: infra-gateway
      namespace: kube-system
    path: ./gateway-infra-patch.yaml
  - target:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: tls-redirect
    path: ./gateway-infra-tls-redirect-patch.yaml
  - target:
      group: gateway.networking.x-k8s.io
      kind: XListenerSet
      name: http-listener-set
    patch: |-
      - op: replace
        path: /spec/listeners/0/hostname
        value: "*.kubevirt-cluster-319.ccsn.dev"
    
