apiVersion: networking.cfargotunnel.com/v1alpha2
kind: Tunnel
metadata:
  name: default-tunnel
  namespace: cloudflare-operator-system
spec:
  cloudflare:
    email: sysops@ccsn.dev
    domain: ccsn.dev
    secret: default-tunnel-secret
    accountId: 579df294982535e588d6ab45d1971da2
  deployPatch: |
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: cloudflared
              args:
                - tunnel
                - --config
                - /etc/cloudflared/config/config.yaml
                - --metrics
                - 0.0.0.0:2000
                - run
              image: cloudflare/cloudflared:2026.5.0
              env:
                - name: TUNNEL_TRANSPORT_PROTOCOL
                  value: "http2"
                - name: TUNNEL_EDGE_IP_VERSION
                  value: "4"
              resources:
                requests:
                  cpu: 10m
                  memory: 16Mi
                limits:
                  cpu: 100m
                  memory: 256Mi

