apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel-dns-binding
  namespace: cloudflare-operator-system
spec:
  endpoints:
    # MUST be patched
  - dnsName: "clustername.ingress.cfd.ccsn.dev"
    recordType: CNAME
    targets:
    - 84bf09ad-68e3-4445-ae54-264d0088090a.cfargotunnel.com
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "false"
  - dnsName: "prod.ingress.cfd.ccsn.dev"
    recordType: CNAME
    targets:
    - 84bf09ad-68e3-4445-ae54-264d0088090a.cfargotunnel.com
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "false"
  - dnsName: "staging.ingress.cfd.ccsn.dev"
    recordType: CNAME
    targets:
    - 84bf09ad-68e3-4445-ae54-264d0088090a.cfargotunnel.com
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "false"
