apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel-dns-binding
  namespace: cloudflare-operator-system
spec:
  endpoints:
    # MUST be patched
  - dnsName: "clustername.ingress.cfd.ccsn.dev"
    recordType: CNAME
    targets:
    - b6db262b-3b33-4400-a381-6d255b81d105.cfargotunnel.com
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "false"
  - dnsName: "prod.ingress.cfd.ccsn.dev"
    recordType: CNAME
    targets:
    - b6db262b-3b33-4400-a381-6d255b81d105.cfargotunnel.com
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "false"
  - dnsName: "staging.ingress.cfd.ccsn.dev"
    recordType: CNAME
    targets:
    - b6db262b-3b33-4400-a381-6d255b81d105.cfargotunnel.com
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "false"
  - dnsName: "prod.ingress.ccsn.dev"
    recordType: CNAME
    targets:
    - prod.ingress.cfd.ccsn.dev
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "false"
  - dnsName: "*.ccsn.dev"
    recordType: CNAME
    targets:
    - prod.ingress.ccsn.dev
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "true"
