# https://fluxcd.io/flux/components/helm/helmreleases/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: logto
spec:
  releaseName: logto
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: helm-chart-logto
  values:
    # We have proxy set up, so we need to trust the proxy headers to get the correct client IP and protocol information.
    trustProxyHeader: true

    dbUrl:
      valueFrom: 
        secretKeyRef:
          name: logto-pg-cluster-app
          key: uri
    endpoint: "https://login.ccsn.dev"

    httpRoute:
      enabled: true
      parentRefs:
        - name: default-gateway
      hostnames:
        - login.ccsn.dev
    console:
      endpoint: "https://logto-dash.ccsn.dev"
      httpRoute:
        enabled: true
        parentRefs:
          - name: default-gateway
        hostnames:
          - logto-dash.ccsn.dev
    resources:
      limits:
        cpu: 1500m
        memory: 2Gi
      requests:
        cpu: 1m
        memory: 128Mi

    persistence:
      # Whether to automatically create the PersistentVolumeClaims exists in the volumes
      enabled: true
      storageClass: ""
      claims:
      - name: connectors-claim
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 15Mi
          limits:
            storage: 500Mi
