# https://fluxcd.io/flux/components/helm/helmreleases/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: logto
spec:
  releaseName: logto
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: helm-chart-logto
  values:
    # We have proxy set up, so we need to trust the proxy headers to get the correct client IP and protocol information.
    trustProxyHeader: true

    dbUrl:
      valueFrom: 
        secretKeyRef:
          name: logto-pg-cluster-app
          key: uri
    endpoint: "https://login.ccsn.dev"

    # Pre-app job https://github.com/the-ccsn/helm-charts/blob/main/charts/logto/templates/job.yaml
    autoSeeding:
      enabled: true
    autoAlteration:
      enabled: true

    httpRoute:
      enabled: true
      parentRefs:
        - name: default-gateway
      hostnames:
        - login.ccsn.dev
    console:
      endpoint: "https://login-dash.ccsn.dev"
      httpRoute:
        enabled: true
        parentRefs:
          - name: default-gateway
        hostnames:
          - login-dash.ccsn.dev
    resources:
      limits:
        cpu: 1500m
        memory: 2Gi
      requests:
        cpu: 1m
        memory: 128Mi

    ## High availability
    replicaCount: 2

    redis:
      enabled: true
      url:
        valueFrom:
          secretKeyRef:
            name: logto-redis-auth
            key: REDIS_URL

    pdb:
      enabled: true
      minAvailable: 1

    podAntiAffinity:
      enabled: true
      type: preferred

    topologySpreadConstraints:
      enabled: false # Only one AZ in our cluster, so this doesn't make sense to enable
