---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pg-cluster.yaml
  - ./pg-credentials.yaml
  - ./objectstore.yaml
  - ./scheduled-backup.yaml
  - ./helm-oci-repo.yaml
  - ./helm-release.yaml
  - ./logto-redis-auth-secret.yaml
  - ./dragonfly.yaml
