apiVersion: v1
kind: Secret
metadata:
  name: logto-redis-auth
type: Opaque
stringData:
  REDIS_PASSWORD: ENC[AES256_GCM,data:AtFxpzRk6pB1WtmiX6HF/Q==,iv:yUy2M42b5DPPmO3nMkSw+Hy4p5+T+QioDjOkMq0t9Cw=,tag:0KLyV/QKHqhw5t36QZps2w==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:FV14OLm3/y67kyVaHmMBg5pQKvEUNo/E3e/gGwmUig9mif2knQEGnO5WV8rse0opaxalMK9rfg==,iv:JrlsMASSmzQuBQE7EILC/XsXKdADWQrtv7RlFt3iSdg=,tag:Tfr9zyhN1NZA2oCyW0eFNw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRldlNm5OQ3VBVlpyTlBo
        STdOQUhTQUo3Vy9aaGJ2Vit3VTNTU2tZMEV3CjhPdHA5dmtPaXFseVdScjhxa05R
        dStMYkducW5JOTcwaTc5MDN0WVlnTDAKLS0tIFRuUkJMNFZMa3lsS3Ntc05jSTBz
        bFg0czh3MVp4V3lVdXVqNjN4UHRXK0EKh55vvuZY68mGvoFA5GPM4vGlpGTQCg1u
        nH2A7wVn3cqlzyKcGT5wpanTQ/2oyrh6tX58pJlfrQR6DZN4NBWU6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T14:11:37Z"
  mac: ENC[AES256_GCM,data:wadJzt8vYytcNfEfswLqb2Bz14nZyO9+45kv25BqNWvIEj9cJMMvFAMR81Ir9DW2huZbf4gjAmd0ILYjjFR72WWF36PP5NbMQzX9wLof+Y1aH7+fEPsRPa+Bm0sI1rko5rvhHOMTwvM3ZcOLUag598KDMkCT+68ssgyXsjhRv9E=,iv:qR+QBUNZWPvOm6IGDKJnstVojN/tkYEtYWykWbquoKw=,tag:LeuzTx8xMAXs3tzxn/Fx8A==,type:str]
  version: 3.13.1
