apiVersion: v1
kind: Secret
metadata:
  name: logto-redis-auth
type: Opaque
stringData:
  REDIS_PASSWORD: ENC[AES256_GCM,data:kfnV0YdDLRNEitl8oeLKVg==,iv:vsC/f+e/nBjp81Nbbdz2dKUh4LZzDJtj08+h/sgtOMk=,tag:B91kKVCBPwEe+IxviQhqJg==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:nCKInsN5DnMK+3EKh0TYTe2OHq7i/WoEW7Sxy22hCS/PjkycGssJKiXlVAiMOJfK/zRs9FQT9XuDCA==,iv:VTGCdmfFQB5k2a3e8l51pDKMyXgDkcogh7xRA6zwzy8=,tag:Uch4zY+KKLOaXNqK9ajDdA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcHZ4UUNrYjVhTnJreTk0
        THprbHpOV2M1bVVaclNTd0gxdHgzWXhUMEFvCitMZjZIT25WNXYyN1pnTU9nRGl2
        TFZjWXFKbU4vOWlRUVFkTCsza1krdVkKLS0tIGJRakRRd1l2cTA2REE5WG4rbFN1
        alVTaFVpcFJoOGhZRFMzdjh0a3Y2SkkK34sb0IMSehQ1vbVNwIGXXZwZqNhozRox
        6Mxut6pR2Hb3PFsTgsCxsI3FnliPC2/dzIP4TJkox/NJ+TVQdJSqKA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T10:26:19Z"
  mac: ENC[AES256_GCM,data:VMhOb9h1PZ8szmbS/LMO+6ZAd0NaMLAOmDED5YnLu3y/1Rk1ZK2THP2pKRK9QIHSuxABop6TqB+s4NEDQSKmlYrfnqmLi9IjW1Y71g1QGFr8BpNjPNGZN0F+BY9ltmSTBQ/aFnEEZkzOfTVB6heokrXwZEefqlV3FHkwvYBa1I8=,iv:mMqIwGrSgJCIYyhneQMshs/U8t9hRytzqaRVbjB5kRE=,tag:XtEgr7E6srMeIkbACzdIXw==,type:str]
  version: 3.13.1
