apiVersion: v1
kind: Secret
metadata:
  name: logto-redis-auth
type: Opaque
stringData:
  REDIS_PASSWORD: ENC[AES256_GCM,data:9JdWBeTvkYLjDQcU5YjNRw==,iv:sjFBHSKOgZf6hOCdys5oIVzXGP3JyWKuu2GajhLDIo4=,tag:9Pmpd0FJ0W5LYXFc9koMsA==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:WR0ncVyJQqt4uG0fP293eRaGWxA2qrDbW9kUFRETiGeABp0BuKlDi5idQ2sN7Df5IO0W3Nd3UAk=,iv:Lx365oxHx80rYFga7VNJyTgPYBu6bgNXAw/IMNcJ258=,tag:Fr1jBFqw+NVKLQNHhH4nIw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSDFnaFlIREMwQnhWdWtC
        aGt4WWRjcEZjdG1rMDFTYTVnNnZ0MFZka2lNCjNkMjB1R24yVitTL2VqVXlsT2d0
        aUZ0NjBRMXF2R0l5VGxrSFh2Nm5mbUUKLS0tIGRDNnJkeGVvUnFub3FYYlNKcHdX
        VHBUZjZCOHdsSFZDOXFrKzhORG9FSFUKo7A87cxVOhOJYcPV/6I6q0vVJdbg3WQk
        CjXh7fTM/9Yl1brQ47IulWPDoZzb4J0HORz6u1D+S+AmZfPlHho1Yg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T09:40:23Z"
  mac: ENC[AES256_GCM,data:WRgxr5V929Y5QiTGeXNKYkYiGER1WtCNnIPIw9m4K46D+KGjyoKkU97OQvvxCaEoMF0lILSHAVyXkc2pHwYsGy+iM5yGrsjeuzH8Eu5+kPhBCgrS9fcPxXg8WFZWMxhnepvzGBpaqLDwTZFRLC8mST7mj1mSeu+qMxuH8CEd33c=,iv:uuT2kHSuToUN2ibgmE++JS6T5FanNGL9sHo0gauF8fo=,tag:uAFEWV7piFAeBgYevJBjZw==,type:str]
  version: 3.13.1
