apiVersion: v1
kind: Secret
metadata:
    name: logto-management
    namespace: prod
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:Cbdnj5e+eqXxRVLTky0Y5KTTZ/qAxiiwrG4RAlD7AeGds4sLDJbOzaCjsaGxoxbTubeRpBMGx5oT1+0b5BT2aDk3RrgLOuSsuJmmo8DCGgzi2e5VLs2hl6cV0VPdQEQ+Vdf2VfHXMYsMlL0Q7/CBcgjsLakxvihvj5ZDJiOw+1REjhjNWtP5V3nl3T0XzvDE0U3hgfFCvh+SvLIEnS77X1kB6/p2atcR465BmZZgxNQOEJ1OZNzY+Cif,iv:L/RUO+VP5QV9dtHwS9zOUWIgrJuXV+cverisMSzJjSA=,tag:72fLI6xuFUVRHvoji/epNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUEg1Q29QOVFva1ZVdzRs
            NkdPTXZUK3R0cHEwcFoxVkR6TW9kU3AwZm13Cm1KNXBHbzZ0c2prYzV1ZlNFYVRt
            RmcwYkNWZS94NmFOd0s4eDMybHlXclUKLS0tIDhxOFpHSUxmWHNXQ2hjMWVjc3lB
            RndZOWtWTnppaXJLZGYxemRpSXZ3cFUK2DmrGNuSLUIOM5p5o2F6yJYj5fRd58OY
            apesmnOXbfrSMXeRrFRiuTXav3oG5yPLq97zcnv0LokV8HhLSI1bbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T18:57:45Z"
    mac: ENC[AES256_GCM,data:YJ6uaPKgNR2rjmTIYt/oTztGOuLqL2OQH9eblJNZfNZYhhwylVR7lKTHbP9QE4PE5HLQAB7iJ0+NlG+E7Y85EyPRmCIe3sE+LawT4XtAVQnR1X8IzOgc7O+eUZqjHvbSYoQEL2and6tEZocGiUVycPj1Sste8dbX5Jzs704aazQ=,iv:pPMWyNx2LZMGSgNSqe3oRN0bwmtsnkxyTqiY+Hklmyo=,tag:j+x5c4McPUmF1Q/naLkQTA==,type:str]
    version: 3.13.3
