apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: logto-pg-objectstore
spec:
  configuration:
    destinationPath: s3://logto-pg-backup/
    endpointURL: https://579df294982535e588d6ab45d1971da2.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: logto-pg-s3-credentials
        key: access-key
      secretAccessKey:
        name: logto-pg-s3-credentials
        key: secret-key
    wal:
      compression: bzip2
    data:
      compression: bzip2
  retentionPolicy: 30d
