apiVersion: v1
kind: Secret
metadata:
  name: logto-pg-s3-credentials
type: Opaque
stringData:
  access-key: ENC[AES256_GCM,data:m6hJrexfkYUcPSpyLE7pvdiC3kBamCTMHKwL9V+H1eE=,iv:kv6Fa78UgQk7qGMge/Fq3obxBxgu7lMAuQ3UAXX0ZLM=,tag:tg5W2OyGH79dZUIyptoSWA==,type:str]
  secret-key: ENC[AES256_GCM,data:eQv3+u7SxWgu77GRfSfKGlp1ZA2d7dK0PEMUdwRW1hqwOpH9g9HVhR6FDjWyIo8uOfzEDEZe+MJQagAV9BQJzg==,iv:aMPBJQ3XvEZFhcQExLJbtbT7ASvacS03F67oe2+Vu5g=,tag:wv5Iuf9Vby/tsk4gaFU9iA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdzV6RVR4Rmh5WFlBazVJ
        QnFHOHJOdnM0QThpa1hEUnN3Q2pjWnNLOVI4CjZhUmV1OXF1TFpnaGtFMnhnRlpC
        bUdUbjZ5ZUEzK2FvK3JHRldwRkNRSTQKLS0tIENjYW9wYnVPRzRjZlJGWlBacW05
        aXpYVm42RlFnTjdCcTFja3dNbnByV1UKtAXClbaKmhIq6ErKCFMD1waMGv34nyX2
        /UuSdaZINb0T1xZjkcpoOeiXQ/n8VQlBoW0xzy+CFeKQNRTLGfaqmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T11:18:37Z"
  mac: ENC[AES256_GCM,data:89mpTwRTqHLAQJqJHiNHhXSV1gYvH0jIy2hiAxYFjIdX7h9PxiG7cKOtPqKDfW+iF1cs2BPikJNQno+SrCbzXFUHLTOESBoNCqJ96Jz26tt3qvOPINf275rFzUfebnO3D8IXB/4LXvRsJ1/uV8dUMgqx1q5Oflm7NIgbK4L3Ge8=,iv:u6eF6ob+ghiMbVVfZpzrlo4udMfwlGNihPJrKcAgcPM=,tag:SQ0H+Nayv2eVa6Lao4I/wA==,type:str]
  version: 3.13.1
