apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: logto-pg-cluster
spec:
  instances: 2

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: logto-pg-objectstore
        serverName: logto-pg-cluster

  # Logto requires superuser access:
  # https://github.com/logto-io/logto/issues/6842
  # https://github.com/logto-io/logto/issues/8275
  managed:
    roles:
      - name: app
        superuser: true
        login: true

  bootstrap:
    initdb:
      owner: app

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    # Logto requires PostgreSQL 14 https://docs.logto.io/logto-oss/get-started-with-oss#:~:text=PostgreSQL,%40%5E14.0
    major: 14

  storage:
    size: 10Gi
    storageClass: longhorn

  enableSuperuserAccess: true
