apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  # The base chart contains the basic CRDs and cluster roles required to set up Istio
  # This should be installed prior to any other Istio component.
  releaseName: istio-base
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: helm-chart-istio-base
    namespace: istio-system
