# https://fluxcd.io/flux/components/helm/helmreleases/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: kube-system
spec:
  releaseName: local-path-provisioner
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: helm-chart-local-path-provisioner
    namespace: kube-system
  # https://github.com/rancher/local-path-provisioner/tree/master/deploy/chart/local-path-provisioner
  values:
    ## For creating the StorageClass automatically:
    storageClass:
      ## Set a provisioner name. If unset, a name will be generated.
      provisionerName: rancher.io/local-path
    
    # pathPattern must start with "{{ .PVC.Namespace }}/{{ .PVC.Name }}/": https://github.com/rancher/local-path-provisioner/pull/542
    storageClassConfigs:
      local-path:
        storageClass:
          create: true
          defaultClass: false
          defaultVolumeType: hostPath
          reclaimPolicy: Delete
          pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}/"
        sharedFileSystemPath: /var/lib/rancher/k3s/storage/default
      local-path-critical:
        storageClass:
          create: true
          defaultClass: false
          defaultVolumeType: hostPath
          reclaimPolicy: Retain
          pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}/"
        sharedFileSystemPath: /var/lib/rancher/k3s/storage/critical
      local-path-test:
        storageClass:
          create: true
          defaultClass: false
          defaultVolumeType: hostPath
          reclaimPolicy: Delete
          pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}/"
        sharedFileSystemPath: /var/lib/rancher/k3s/storage/test
      local-path-nocow:
        storageClass:
          create: true
          defaultClass: false
          defaultVolumeType: hostPath
          reclaimPolicy: Delete
          pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}/"
        sharedFileSystemPath: /var/lib/rancher/k3s/storage/00-nocow/default
      local-path-nocow-critical:
        storageClass:
          create: true
          defaultClass: false
          defaultVolumeType: hostPath
          reclaimPolicy: Retain
          pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}/"
        sharedFileSystemPath: /var/lib/rancher/k3s/storage/00-nocow/critical
      local-path-nocow-test:
        storageClass:
          create: true
          defaultClass: false
          defaultVolumeType: hostPath
          reclaimPolicy: Delete
          pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}/"
        sharedFileSystemPath: /var/lib/rancher/k3s/storage/00-nocow/test

    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 1m
        memory: 32Mi
    configmap:
      # specify the config map name
      name: local-path-config
      # specify the custom script for setup and teardown
      setup: |-
        #!/bin/sh
        set -eu
        mkdir -m 0777 -p "$VOL_DIR"
        if echo "$VOL_DIR" | grep -q "00-nocow/"; then
          echo "Disabling COW for volume path: $VOL_DIR"
          chattr +C "$VOL_DIR" || true
        fi
      teardown: |-
        #!/bin/sh
        set -eu
        rm -rf "$VOL_DIR"
