apiVersion: application.logto.m.crossplane.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: prod
spec:
  managementPolicies:
  - Observe
  - Create
  - Update
  - LateInitialize
  forProvider:
    name: Vaultwarden
    type: Traditional
    description: ''
    isThirdParty: false
    redirectUris:
    - https://vault.ccsn.dev/identity/connect/oidc-signin
    postLogoutRedirectUris: []
    corsAllowedOrigins: []
    oidcClientMetadataExtra: '{"backchannelLogoutSessionRequired":false}'
    customClientMetadataExtra: '{"idTokenTtl":3600,"refreshTokenTtlInDays":14,"alwaysIssueRefreshToken":false,"rotateRefreshToken":true,"allowTokenExchange":false}'
  providerConfigRef:
    name: ccsn-logto
    kind: ClusterProviderConfig
