apiVersion: application.logto.m.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: vaultwarden-credential
  namespace: prod
spec:
  managementPolicies:
  - Observe
  - Create
  - Update
  - LateInitialize
  forProvider:
    name: GitOps
    applicationIdRef:
      name: vaultwarden
      policy:
        resolve: Always
  providerConfigRef:
    name: ccsn-logto
    kind: ClusterProviderConfig
  writeConnectionSecretToRef:
    name: vaultwarden-oidc
