apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "1h"
    fluxcd.controlplane.io/reconcileArtifactEvery: "10m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
    image-lock/extra-images: >-
      ghcr.io/fluxcd/helm-controller:v1.5.5,
      ghcr.io/fluxcd/kustomize-controller:v1.8.5,
      ghcr.io/fluxcd/notification-controller:v1.8.4,
      ghcr.io/fluxcd/source-controller:v1.8.5
spec:
  distribution:
    version: "2.8.8"
    registry: "ghcr.io/fluxcd"
  sync:
    kind: GitRepository
    url: "https://github.com/the-ccsn/k8s-gitops"
    ref: "refs/heads/main"
    path: "clusters/kubevirt-cluster-319"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  cluster:
    type: kubernetes
    multitenant: false
    # Istio trasnport data on port different from the original one,
    # so we need to disable network policy to allow traffic between controllers and Istio
    networkPolicy: false
  kustomize:
    patches:
      - target:
          kind: Namespace
        patch: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: flux-system
            labels:
              istio.io/dataplane-mode: ambient
