apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
type: Opaque
stringData:
  apiToken: ENC[AES256_GCM,data:b2axrqP1aOWwCwGbSALX0RRTRl3CN7zGf8GLhUGxgYCfaNCbClN3q1vDdKQueZaFnlG90x8=,iv:FvDd/uV7TOi5JwBtExhoa4SV7QnR9lkEuLePdwlv0OI=,tag:8kiy5fMu9CmsfbX3G6UYKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtU2NjOWRXY0tYVkErZ016
        dU5kRHh4eWhJZCtjTmJNOCtiS2IxOFUvQmlvCjIrRE1oaE9mZ0VWYjBYeE5qWnBT
        SlZDVjJmRld4UTVkMDFzMzVYQUdNam8KLS0tIDluOUxmUjNWQmM4YmFLSStZVXpO
        bWVDN2NFMXRET1k5dEtOeGxaMFhIOUEK6lNW5PBxa/CQo3mMEg0kFMDBdvAbGkKV
        xRH3GDdaX+31VzGLdOax8lLu1Yph2mNFMERyobJxEdYyXO3Rkltmfg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T14:43:15Z"
  mac: ENC[AES256_GCM,data:KRQU/Tg6deS4l+ks6aaZHsHa0p2URP7z/m+21NRE91ybx1DvZJG5RH1KxriWiLi9ZUNW2izQZKTxc0fehIxCXLQ5P2imavozMuphJcwMPubVmbhE7Dx/zx0gvuBlorWmjkIPfgYDTgc2kHHEAIpLbIRdwMvkA+y6lmQrqqG9jb8=,iv:P44UJRkhbTLLvS4KlNsNuO7jRYdyaBSOHxRTBF30a+k=,tag:suK6Pwt7dwKC5Kwj51zPFQ==,type:str]
  version: 3.13.1
