---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helm-chart-oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 12h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/oauth2-proxy/charts/oauth2-proxy
  ref:
    tag: "10.6.0"
