apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
type: Opaque
stringData:
  cookie-secret: ENC[AES256_GCM,data:HyNXwChlOSU+GqaLLnu9XvCZ+J9YwypWEkScg89jca6t9Zs5X8kr3I1I9O4=,iv:O2xB+fROq1pK3dqJ99WX1+octgm0tWtB56YlFDJ8m6I=,tag:FkoD1K0V4hQeV64mfhCIaw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVWZoNFJSaTh6cG5VSVQ0
        bUxyNk4yTXpsNmxWZ2dIRVQyalpaZDRzVUhvCmMxMFBkYzUrZGJ4T0VVd0hHWGdS
        cVlXRis3dHNPcmxjZWhnRGNzeE5ZbXMKLS0tIGJmSy9MRHc0ZHMyQ1JlbmxUNDRL
        VHNGNlR6bDZjRFJjSHNEUTVKTlZEWm8Ke71FITv6vSjQNYzUwbxdWwDUq1kv285T
        xu21Mr93spmOwrqPYY/vo8/P2gCdGVqzXJW/de8zsQXfxgYuNzLqGQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T12:48:35Z"
  mac: ENC[AES256_GCM,data:fMNd9oCeijjf+F7vRt43NP8AR9FXkc1XByu2YH7KVDi0u/W00Uney74Fb12gWcOQDQ+viDom/0W6HbmLZ1YX7EYc8EV+e6JPZlA5+KWcwvvcCiZKn0CK5GnrVpkU22TOcS++7Hr7Kf2QG4MqoJjEDngHuqX8RSns8yQ5IkBBkcc=,iv:SgY1Pi4RdxWyXwhMfxXrinPSZsi5fbtuPa6e3OGUD/Y=,tag:+hfx713lKU4MrRofiKqMww==,type:str]
  version: 3.13.3
