apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
type: Opaque
# cookie-secret: https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/#generating-a-cookie-secret
stringData:
  client-id: ENC[AES256_GCM,data:DGz4cATMo2h9GHuAHZIgXpiuJDXy,iv:54hg4YrO84y93dHxh2Dj0H0A0b6EzOF1LwcosSeW/LY=,tag:jo40+SYH0tpUK/utQ7JTxg==,type:str]
  client-secret: ENC[AES256_GCM,data:r3ulcq0qLFL/PuYT1OItAtSrcTrS8GlXGIt4IyZK8JE=,iv:dSr0ov/MQreSiKJpNIdU1cxM0wApqUwQKiw1us7agjg=,tag:akGsjFGMAhndkB0jOzZ82g==,type:str]
  cookie-secret: ENC[AES256_GCM,data:6/eXwZr/NhQkMedLqgv5bnLXLsm7NPOh6nOT/AwuJ4wpq1byqAqwEs9vYwA=,iv:Ym6nrfznZNBx1rxAovp4mK4iaRDlBny3YwOEv6t7TtU=,tag:qzNzWar3cGaYQ7eQ3WNksw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArc3M4eXAwcThCUWkwcVFD
        MkltVEwraWQ4bHplcjZiNytySWN4Zm9FSEVNCkc4bXB3K2JGT0R0K3h3TDFMVk1h
        eGhYQmFlUjJ6dlU1a2x6OEFGTXlHS3MKLS0tIHVEOHBOZnE2azRSaDBpMkUzR3c5
        cnlHYnliT0l3bXZhVjlGZEJ0c3QwMUkKdIuL/SvCLQRt+q4iiJvaqrYYUsBjqazw
        yVYbRwNJU7KY6iiXAWYQhkkYh1Cnyre+2xK4mO6EDq41O/K8KqtP7g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T07:25:46Z"
  mac: ENC[AES256_GCM,data:KRvx4n5asuia5geHCH3ZmF7dSyJAOOsBzfq6nag91KSJEPNrK/AQuorVmnQfAA+hYbZDn0GvTJ/8AgrhUgFW8I/vx+JDaxF78lj2ZJE2utiFLkj8cUsg2SG2uHL7O9fAQXwhaCT6d81O56X4Uq+LIChQ9zEeUXVhHoR2JR/4MvU=,iv:OFyUwGrO5oQqxVwoPqATGOzrnFlbQe0VkIMNigDWZ+s=,tag:CcS8mXoQi93J8YIcNQbbHQ==,type:str]
  version: 3.13.1
