---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-egress
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: v1
kind: Namespace
metadata:
  name: kiali-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt
---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-network-addons
---
apiVersion: v1
kind: Namespace
metadata:
  name: cdi
---
apiVersion: v1
kind: Namespace
metadata:
  name: k6
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-database
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-operator-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: i319-reroute
---
apiVersion: v1
kind: Namespace
metadata:
  name: redroid-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
---
apiVersion: v1
kind: Namespace
metadata:
  name: egress-system
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
