---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: proxy-engine-dashboard
  namespace: egress-system
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: default-gateway
      namespace: prod
  hostnames:
    - proxy-engine.ccsn.dev
  rules:
    - matches:
        - path:
            type: Exact
            value: /
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /ui/
      backendRefs:
        - name: proxy-svc
          port: 9090
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: proxy-svc
          port: 9090
