apiVersion: v1
kind: ConfigMap
metadata:
  name: sing-box-main-config
  namespace: egress-system
data:
  # `route.auto_detect_interface` MUST be `false``, otherwise the proxy will detect the default network interface and bind to it,
  # which will cause network unavailability when service mesh is enabled.
  main.json: |
    {
      "experimental": {
        "clash_api": {
          "external_controller": "0.0.0.0:9090",
          "external_ui": "dashboard",
          "external_ui_download_url": "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip",
          "external_ui_download_detour": "AllNodes",
          "access_control_allow_origin": [
            "https://proxy-engine.ccsn.dev"
          ]
        }
      },
      "dns": {
        "rules": [
        ],
        "servers": [
          { "type": "tls", "server": "one.one.one.one", "detour": "AllNodes", "tag": "remote", "domain_resolver": "local" },
          { "type": "tls", "server": "dot.pub", "detour": "direct", "tag": "local", "domain_resolver": "local-raw" },
          { "type": "local", "detour": "direct", "tag": "local-raw" }
        ],
        "final": "local",
        "disable_cache": false
      },
      "outbounds": [
          { "type": "direct", "tag": "direct", "domain_resolver": "local" }
      ],
      "inbounds": [
        {
          "listen": "0.0.0.0",
          "listen_port": 7890,
          "tag": "mixed-in",
          "type": "mixed"
        }
      ],
      "route": {
        "auto_detect_interface": false,
        "default_domain_resolver": {
          "server": "local"
        },
        "rules": [
          { "action": "sniff" },
          { "protocol": "dns", "action": "hijack-dns" },
          { "rule_set": ["anthropic", "google-gemini", "google-deepmind"], "outbound": "UnitedStates" },
          { "rule_set": ["geosite-geolocation-!cn"], "outbound": "AllNodes" },
          { "rule_set": ["geosite-geolocation-cn", "geoip-cn"], "outbound": "direct" },
          { "action": "resolve", "strategy": "prefer_ipv4"},
          { "ip_is_private": true, "outbound": "direct" },
          { "rule_set": ["geoip-cn"], "outbound": "direct" }
        ],
        "final": "AllNodes",
        "rule_set": [
          {
            "tag": "geosite-geolocation-cn",
            "type": "remote",
            "format": "binary",
            "url": "https://cdn.jsdelivr.net/gh/SagerNet/sing-geosite@rule-set/geosite-geolocation-cn.srs",
            "download_detour": "direct"
          },
          {
            "tag": "geosite-geolocation-!cn",
            "type": "remote",
            "format": "binary",
            "url": "https://cdn.jsdelivr.net/gh/SagerNet/sing-geosite@rule-set/geosite-geolocation-!cn.srs",
            "download_detour": "direct"
          },
          {
            "tag": "anthropic",
            "type": "remote",
            "format": "binary",
            "url": "https://cdn.jsdelivr.net/gh/SagerNet/sing-geosite@rule-set/geosite-anthropic.srs",
            "download_detour": "direct"
          },
          {
            "tag": "google-gemini",
            "type": "remote",
            "format": "binary",
            "url": "https://cdn.jsdelivr.net/gh/SagerNet/sing-geosite@rule-set/geosite-google-gemini.srs",
            "download_detour": "direct"
          },
          {
            "tag": "google-deepmind",
            "type": "remote",
            "format": "binary",
            "url": "https://cdn.jsdelivr.net/gh/SagerNet/sing-geosite@rule-set/geosite-google-deepmind.srs",
            "download_detour": "direct"
          },
          {
            "tag": "geoip-cn",
            "type": "remote",
            "format": "binary",
            "url": "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/srs/cn.srs",
            "download_detour": "direct"
          }
        ]
      }
    }
