apiVersion: v1
kind: Secret
metadata:
  name: sub-converter-suburls-secret
  namespace: egress-system
# Separate multiple sub-URLs with comma, and each sub-URL is in the format of "name:url"
# Optional: set NODE_SELECTIONS like
#   HongKong = [ 'HongKong URLTest', '[YZT] 香港1', '[YZT] 香港2' ]
#   UnitedStates = [ 'UnitedStates URLTest', 'My US Node' ]
stringData:
  SUB_URLS: ENC[AES256_GCM,data:2pD223d3/1TeaavQcODSC8gGzfhK7ipUabxh6W4VpyyIIIZL/gxKuqh1JqDGZm0/muvRGGxkaR6X6hjnUO2ySUr6xusdXHSOW9z3uf5Dv322se+OjqCr3S6Mdr50PSCQdJFznNr1jSk1ocKK59cbOcMgj/NbO0hwDKupb/U9DnvyVzsAUAJ6VFAe81c6+561fCz6UNYEDSmL1ax62SkE1bfh88Js,iv:11m9ZfRbwjz+yZfZ6DINJKxaMESQO6ba/i9LgSgyYP8=,tag:PAssYTkk92Me1bSsCk0kEQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScVcwYVkzdmxhNGpyZXJS
        ZnJqOEhMb05KWEh1cHZBR1NCcWd3di9lVzNJCm9Oclk0eGYwNE42UXVWMXZFdzI4
        dEVLc0MzWkl6SVdxbHplNmpEQnVvbXMKLS0tIHMvNElUQ3V5YUErclV0VldqVkZI
        ZE5aMzBibDB5T3J2YkZLdEZvQkFRSkEKSv0WcVC5zkJTdNa8NCcdF+zjNXeKeCYf
        gjEeMoJGTVMEOxM1ZOjcLfX8kZWQmzSvzR6bjMIhI9dnw//jtRO1ZQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T14:15:19Z"
  mac: ENC[AES256_GCM,data:v6+BchdKzZ+Td5HAlunCzZ12Gb1Vo2elFXp+yo/EHSAdt4TuOOvXnHcXa4hx9AOdAcAFUbXKKyTBPxF8pWTFXD9osRynNpgx6TZQVUducnbDd4LwMhzej1zzkY89IFdEKgpt5boISmJWa731d0sztHTympvYmyISwmckyYv0ZQ8=,iv:ll6Z9Eui2pmfABX8HeLXuEwfFbQPXX9yv0QwxaGyxWE=,tag:AWWK2fkXuU6tNaGAA4CORQ==,type:str]
  version: 3.13.1
