apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxy-engine-work-cache
  namespace: egress-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
