---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # deploy monitoring stack first
  - ../../base/generic-device-plugin/
  - ../../base/grafana-operator/
  - ../../base/victoria-metrics/
  # TODO: re-enable after S3 or MinIO is deployed
  # - ../../base/loki/
  # - ../../base/otel-collector/
  - ../../base/longhorn/
  - ../../base/cert-manager/
  - ../../base/gateway-api/
  - ../../base/istio/
  - ../../base/kubevirt/
  - ../../base/cloudflare-operator/
  - ../../base/external-dns/
  - ../../base/harbor/
  - ../../base/cloudnative-pg/
  - ../../base/redroid-operator/
  - ../../base/egress/
  - ../../base/kiali/
  - ../../base/oauth2-proxy/

patches:
  - path: ./helmrelease-victoria-metrics.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: victoria-metrics-k8s-stack
      namespace: monitoring
