---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helm-chart-victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  interval: 12h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
  ref:
    tag: "0.79.1"
