apiVersion: v1
kind: Secret
metadata:
  name: default-tunnel-secret
  namespace: cloudflare-operator-system
type: Opaque
stringData:
  CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:ipUVTmqZHEz6vzWcBXXFaygw1Cp/i+rJjtDy7M6vMaSzW7jbXtOQwg==,iv:g/9nym5GJF+mkyTlsQHQoWQEQa/kAAhIb2qddeprang=,tag:qrDyaAmcoZP9LIDeOzABFQ==,type:str]
  CLOUDFLARE_TUNNEL_CREDENTIAL_FILE: ENC[AES256_GCM,data:aeZmVJpeoyMCbAEQQL+mNMcWAe6WODtVzZNgdEppK5cP8Cmwu2JuwDiOdPs/ZZKrHs8aR6f6DyBw47LvwtZDL9HKAitldyZbAds4GGS5fR5NJHJkv2rUxLzf5QN8fHxOMVXDxsPhpbCJICREQWOroBK2NREmfhTOHT6fOVtBJ3mhRIUUfdQyLwg9hLGCmF6MPBBscDlVQy3r8LfYB4oiafNdcJumWfYjy4wjS86t516Rq/XIjWvB07rebDve/FZZJq5X0HaN,iv:bL/x5HA1axyXRR6tG7BShH2ztu6gzziym/Jz6C+6z78=,tag:p3hiZw0GdxOxEsYjWi8G3w==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaGtUSnhuTjYrVEp4LytR
        QzVQaTFRZ2Z4bkFJOEdQWlRHS2xXYmlCUW5zCnlDMVhzL3lHd2xSaU1HWCt2Z3Vp
        eXRoWGpnVzZUM2JFeWRyVURrM3ZCWXMKLS0tIFQ4S3hKaDNURCtRYW13ZGpTd2RT
        MDVHUjFrN1lBblFWS2JSbmsvcnlHZXMKSmchCsrfagcdCMSkaccfqkWC1ZFDFuZX
        BRuIKkxHxeASZRpXV4YiDy5QmjcrY1WHbwaINFMhMv2pEzCBH4CNww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-21T15:07:45Z"
  mac: ENC[AES256_GCM,data:tPHgjwsk+W+CVU07UVf1P2TdDFAbBX6cKswWotF0SZOAPZfrnfW36MTykNgtnweqmlczmuS1LtZAFLwSFJrzYYcLdqp6bPheJnUdXvIKtEHVRQxJhSz64RUwt+rs6eLuCVEMaBQxsadJe5c9ALs/G2LSd81SfelKyrwTziHbtvU=,iv:LyZG74bSNdNFlfo5tMDTXWOY/+t/1sIPdFhED1rhJmY=,tag:1AasfO8FaD037NI4cDGP0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
