apiVersion: v1
kind: Secret
metadata:
  name: default-tunnel-secret
  namespace: cloudflare-operator-system
type: Opaque
stringData:
  CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:oQJhq5A7CCaS3OPp/yKzmGeY1fTbvgesdvd0TF4SfeJj46PaOyxmvzGWqAoSFQM8E8rVxUU=,iv:C7/PaYHP1XV/7RF7TePcHBDumBRMFp42i/p2zLGYSN4=,tag:T/6OzsfHKNlJYjY0n2jw1g==,type:str]
  CLOUDFLARE_TUNNEL_CREDENTIAL_FILE: ENC[AES256_GCM,data:G2IJ/9mK7LU4asnPko5bU1nxHP5fhOkdXItvUgaUHQtgEszMPf8/st/Xplxmt8Pkvs86v/rbS7bkTWcaxw2iMj7A30ukXj8FPqZYF2GQv+2/nyYMZNJJfuqmUR0KB5g6AxhcsPmMes2sXnVQrGS2f5kr1wC/q93ZbbzwlrYJINntKLJuiEjLQiHiIeSrzGN7HtTEGqNS4LaHhm65ZnyBiHXi3Igo6Hjljiek8Vwtsha86a6/VY2Veimx7W8yoLUwFjYFxi/KipbMjUqO,iv:cn0oVYwqGhGI6XzDfRwhkkzxhL/v1rB7KU7O8Ty1nWo=,tag:4L+/0Za+l9Z5R++5JgbaPA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYk4rNVQwRFVWVnAwNi9n
        ajc2eDFYOFJPN2w2RU1QdlZOYWZTUTdmTnlvCmxsUG9VaW5sSVpNVk0zUVNEZDBY
        QWFzME0vY3MvekdVRzEzU2FrTEF3aFEKLS0tIHhmSmJvRzUvOUFPTWNabDhwZThz
        Ulpmd0FuWUJVNlI2a0E2N3hRUVhuVEUKfyY6m3LZJRRHUh6Y85SRe4d3LC6D/AzX
        OctJnpxk+uvdeYrRtDT5ZlteWKPK7QD65t2axlVuy2a1vHBtzE60AQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T08:26:40Z"
  mac: ENC[AES256_GCM,data:DFiGEzdmViM4rI4h9YfLgEvy62GeoR1uU/lX9OilvM5KhbpPScKITerCrto9nsqb4gDGtNdCB/OBZaf8BF26SPIfGIQ1fEQ+T3i9Z19mEIGTDIV7yAC3Hqr6G1GGayrxLAtcAq79jg2k4c9Z9J/AI3WXzql8zU16isjLRWsCoZQ=,iv:aGFRcTxVbAF3A+oKjt5UNgvsW9ZHu6Fq9OTiaKr+KxY=,tag:61XPX0KfRZz1UxE52TMqKA==,type:str]
  version: 3.13.1
