apiVersion: v1
kind: Secret
metadata:
  name: default-tunnel-secret
  namespace: cloudflare-operator-system
type: Opaque
stringData:
  CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:zrM1DVIHbuuEcefs6qhCHZqRLpjdRIt0dvNy+k8sXX5qq2m5C1oFnu3AcJO8w7noOfeid54=,iv:IlaNIkGHCOgGS0vbWIZT9+yYlZ9NW5/seo+toziBHiU=,tag:Gn2cSy0OMWsNdHmm8Vc79Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza2V0L1NZdkpIRnk5ZURC
        dURDRHJLdVBBYTl3N3ZiVnVmcGZRcDFCeEcwClpPY0lheERzSHRTZGlHeUhGYmFZ
        MlNVS0RlVjB3cWlQMTFPaGFDSklnUkkKLS0tIDNtTXhZM0pBaGVOSGpxRHRnVXBz
        Qi9RNjJDL21XWE9Jd0dpV3hTNy9wR00Kn3BrdJ0wMHmlgL3fAclgN/WQhF5dnjII
        BgsJPWJlphRXy9nfH8d6VC3BKOeSdI3zt/HUPfG8LOnHOxgOBFpX/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T14:33:08Z"
  mac: ENC[AES256_GCM,data:gQ0IqMNJuJOY0d5eN7dJ4v7OkkqD6atbaqeq/0wiAsuqhgffbRfdQHuGdt+S3FYvuxeh3r8u6jptLZtBJe62gYtmx53evX4wT8/CfjpHtSKxje1lY22tV7uOC6ULCJCAOmhuuc3qSJzin47UCSBM13gHoXrlz1NhUz4AtgXTEBQ=,iv:+dFf67yGOmV2olI+Qhm2FcHuI7yEX5BvBQVYEQd0QlQ=,tag:7xNLHs2qrXRiMRrpoCCmnw==,type:str]
  version: 3.13.1
