---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager/
  - ../../base/egress/
  - ../../base/external-dns/
  - ../../base/gateway-api/
  - ../../base/generic-device-plugin/
  - ../../base/harbor/
  - ../../base/longhorn/
