---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager/
  - ../../base/external-dns/
  - ../../base/gateway-api/
  - ../../base/generic-device-plugin/
  - ../../base/longhorn/
  - ./longhorn-hdd-nodes.yaml
  - ./longhorn-hdd-storageclass.yaml
  - ./external-dns-campus.yaml

patches:
  - target:
      kind: Deployment
      name: external-dns
      namespace: external-dns-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --annotation-filter=networking.ccsn.dev/dns-scope notin (campus)
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --exclude-domains=ingress.319.ccsn.dev
