---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helm-chart-cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 12h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
  ref:
    tag: "0.28.2"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helm-chart-cloudnative-pg-plugin-barman-cloud
  namespace: cnpg-system
spec:
  interval: 12h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/cloudnative-pg/charts/plugin-barman-cloud
  ref:
    tag: "0.6.0"
