apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: flux-iac.github.io
  namespace: egress-system
spec:
  exportTo: ["*"]
  hosts:
    - flux-iac.github.io
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: TLS
  resolution: DNS
---
########### HTTPS traffic to flux-iac.github.io ###########
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: direct-to-encapsulated-https-flux-iac.github.io
  namespace: egress-system
spec:
  parentRefs:
    - kind: ServiceEntry
      group: networking.istio.io
      name: flux-iac.github.io
      port: 443
  hostnames:
    - flux-iac.github.io
  rules:
    - backendRefs:
        - kind: Hostname
          group: networking.istio.io
          name: flux-iac.github.io.encapsulated-https.egress-gateway.mesh.internal
          port: 443
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: encapsulated-https-flux-iac.github.io
  namespace: egress-system
spec:
  exportTo: ["."]
  hosts:
    - flux-iac.github.io.encapsulated-https.egress-gateway.mesh.internal
  location: MESH_INTERNAL
  ports:
    - number: 443
      name: https
      protocol: TLS
  resolution: DNS
  endpoints:
    - address: proxy-svc.egress-system.svc.cluster.local
      ports:
        https: 7890
---
# Encapsulate the egress traffic into CONNECT tunnel to forward all traffic to it.
# Applies to HTTPS traffic to flux-iac.github.io.
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: encapsulate-https-flux-iac.github.io
  namespace: egress-system
spec:
  host: flux-iac.github.io.encapsulated-https.egress-gateway.mesh.internal
  exportTo: ["."]
  trafficPolicy:
    tunnel:
      protocol: CONNECT
      targetHost: flux-iac.github.io
      targetPort: 443
