apiVersion: v1
kind: Secret
metadata:
  name: harbor-k8s-robot-credential
  namespace: harbor
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:JDc9xF1P6mBFicUslsNWP7LpUx78M1VmiICgaqaNbsA=,iv:htsCRSYHD4pFSoXSOR+neR3D2V52g5hkiu6kqX99wP0=,tag:He16j+YjR3n4nFRfxNf4sg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdjQya1cvb3pPTTg3S2Z0
        YlJqTk14ZWJWTEpucVhYNG02VHM1di9BTHd3CmFOcGZkZmlwZGxSK25tWkFhYUJY
        STFLazNDazNEcTdhbU12cWNManl0bWMKLS0tIEVEd0U2NFV5MytudkxUamNHK3RY
        WGdScytPSEZFY3hLS2x0c0kzVXBJT1kKY6BIdc9l9dDUMLb3rce02VkZyVcRlUD4
        CjL65CHYMR0/qbUQfDxn2VibLvl9VyeZ8+XpX51LJkIgd3MdOtPHXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T04:22:14Z"
  mac: ENC[AES256_GCM,data:ASQjg/JfyC9rd9s2oBqS6M4QOKG2nwpV2sqNMJDiL1hQSquO+fOCCSc4zZApvb3oy/HdtZusQuJ/3Djv3UzZqCpC5c9RJ8tFJSdQgSMzftFSWrNVR5oecgBBHXdS7ZoRL85W9oKDAGdKpcu6XE1OF8f9pUrKaGry1CxbNtLLpvY=,iv:f2GMZrTwNaAHN3UKkZStfqh1QaL5rg5xzCVmJO7fdkw=,tag:CYwJFb2bJOmWYK+ABzItuQ==,type:str]
  version: 3.13.3
