---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  releaseName: oauth2-proxy
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: helm-chart-oauth2-proxy
    namespace: oauth2-proxy
  values:
    replicaCount: 1
    config:
      forceLegacyConfig: false
      existingSecret: oauth2-proxy-secrets
      emailDomains:
        - "*"
    alphaConfig:
      enabled: true
      configData:
        upstreamConfig:
          upstreams:
            - id: default
              path: /
              static: true
              staticCode: 200
        providers:
          - id: oidc
            provider: oidc
            clientID: ${OAUTH2_PROXY_CLIENT_ID}
            clientSecret: ${OAUTH2_PROXY_CLIENT_SECRET}
            scope: openid profile email roles offline_access
            additionalClaims:
              - roles
            oidcConfig:
              issuerURL: https://login.ccsn.dev/oidc
              groupsClaim: roles
            profileURL: https://login.ccsn.dev/oidc/me
        injectResponseHeaders:
          - name: X-OAuth2-Gateway-User
            values:
              - claimSource:
                  claim: preferred_username
          - name: X-OAuth2-Gateway-Email
            values:
              - claimSource:
                  claim: email
          - name: X-OAuth2-Gateway-Groups
            values:
              - claimSource:
                  claim: roles
          - name: X-OAuth2-Gateway-Id-Token
            values:
              - claimSource:
                  claim: id_token
          - name: X-OAuth2-Gateway-Access-Token
            values:
              - claimSource:
                  claim: access_token
    extraArgs:
      redirect-url: "https://oauth2-gateway.ccsn.dev/oauth2/callback"
      reverse-proxy: "true"
      skip-provider-button: "true"
      cookie-secure: "true"
      cookie-expire: "168h" # 7 days, no support for 'd' suffix
      cookie-refresh: "15m"
      cookie-samesite: "lax"
      cookie-domain: ".ccsn.dev"
      whitelist-domain: ".ccsn.dev"
    gatewayApi:
      enabled: true
      gatewayRef:
        kind: Gateway
        name: default-gateway
        namespace: prod
      hostnames:
        - oauth2-gateway.ccsn.dev
    resources:
      requests:
        cpu: "10m"
        memory: "64Mi"
      limits:
        memory: "256Mi"
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      enabled: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
