apiVersion: application.logto.m.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: flux-web-credential
  namespace: flux-system
spec:
  managementPolicies:
  - Observe
  - Create
  - Update
  - LateInitialize
  forProvider:
    name: GitOps
    applicationIdRef:
      name: flux-web
      policy:
        resolve: Always
  providerConfigRef:
    name: ccsn-logto
    kind: ClusterProviderConfig
  writeConnectionSecretToRef:
    name: flux-web-oidc
