apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:alfZu8w=,iv:ePN6CriUFtc5W1hRjwBFWcVaZo2XUzoWiaJFI+bPTvE=,tag:DjuXnp0iPd36WDmWOUteVg==,type:str]
  client-secret: ENC[AES256_GCM,data:w8FTgnQ=,iv:Zx/Jv4K7ycQ6mj1l52l1L+0qoxbrV+mFTwQh6OVP1ts=,tag:5FjhCyy8D72Gs9DiQRyxeQ==,type:str]
  cookie-secret: ENC[AES256_GCM,data:hYMZBOE=,iv:V5/2Lgbe6UfO3efLORBQE2WLMXLszhLOTLrKdO+ZMCo=,tag:XzVMIad9C+o0COlriRvsJw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUkhHd3lCUVFLNUNNaVpD
        MkZiRlNGajU1dzl3V1BqNy9lOVJpbzEyemtNClZKM3J6WkxhV01ycG5DWkhPV0ZB
        NzhpdXpQMGc0NUhFU0NWRlYyV29lR1kKLS0tIEdvS0dXb0hkR0ptcXU5bU03R0ZY
        ZGNrRXd0YjQzVkdFek55b1JPWEJyaTQKJEZvtKPv4bxaAIP1bm/dkTASKBxdo1d7
        m776wmAlXmAxol+iUkefSAlYpTxcCNgPThIPu7WlNuT5l+ZTCj1pvA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T14:23:44Z"
  mac: ENC[AES256_GCM,data:2VP2JnplvRX3R70CGEOYZK62cso1hGSjE8pIoTIcYuh/MOEZNFSL/UvleBY/gnPd+7k+DX6knT9KOhHhtWOnoeDXFK+qTXIzyUgBZmoc5pq0Hgbc1UEu9/VqTZpgfRey3C40xhe7J435arq8fnIAP6NzXDv1dBStBjB/bYOVx+Y=,iv:uzfyUrTQtX9ee/NN1qTnst/4ANI1Ey+z/eK5wAWihyc=,tag:m9ZQbcRVuLkEfIQzZUoVhw==,type:str]
  version: 3.13.1
