---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8s-gitops
  namespace: harbor
spec:
  interval: 1m
  url: https://github.com/the-ccsn/k8s-gitops
  ref:
    branch: main
