apiVersion: v1
kind: Secret
metadata:
  name: harbor-oidc
  namespace: harbor
type: Opaque
# This key is merged into Helm values via spec.valuesFrom.valuesKey.
# Keep configureUserSettings as a single-line JSON string value.
#   values.yaml: |
#     core:
#       configureUserSettings: '{"self_registration": false,"auth_mode": "oidc_auth","primary_auth_mode": true,"oidc_name": "SSO","oidc_endpoint": "https://login.ccsn.dev/oidc","oidc_scope": "openid,profile,email,roles,offline_access","oidc_client_id": "534gp0torf1s2dsokwcwo","oidc_client_secret": "[REDACTED]","oidc_verify_cert": true,"oidc_auto_onboard": true,"oidc_user_claim": "username","oidc_groups_claim": "roles","oidc_group_filter": "^harbor:[a-z]+$","oidc_admin_group": "harbor:admin","oidc_logout": true}'
stringData:
  values.yaml: ENC[AES256_GCM,data:CAjgcDQf1aLKT9BTEh7BFktbz4Q32+XV9G3rlntO2X/PltspYIoHiFR2F50Cw0pjzUeC6juQCmZqb2dUA1z1LCzvOBHq9eD09pr3t/aTAIrfvimj7NTjdO/+dckUVam33f5iu6Wg+PNhc4roxNkQkclxoTOE21gPiGuzVz6Q7KQurmj+Y29CreEmtM9cymPrfge/hg7SvVOSEYsNT7t8pg4YcIhxho1psvkrNdNsNVNlqXUwK88qDE7ljlLwXbQ5rtCUrR/YoksfhDzqEgOMDlN3kWIV9UVrd3ptPcJwfO37uE+KUrIBWDewzKYZSOMYMRKQETZw0KX4PkAZQdA1q9KbOQ5I0MNjfRVSJFxYE0TAE6L8CB4+qmqdiZ3JdyxiqgF5ZjD3KJpOmFh0F7ZKlzRFNSqJMKVohqZSYt0a148riuRoF/ZgzPFnQWeDH+jJor3gySLCNjACzsIjccWT1nDChNnbk99JqSTsLYzNkjJIxNFZ0wfYc/HiVd2nZV6zJp3w2jS9J4EVR5i0/iMQy/RaagsO8NKIhKlFuvtcJ9mzMAkCLm4PbDen+773TN++3JhTm4jQmhs24BcjfCKoYURwLbdJcHA1CBA5X8UyLxFaTKSHlf+O+h+E2x5+oaxkvCwc5x2Ui78jhQrNV3WqnncNjVxysvdzSI65k4iPM6UvU4qvkjoM7AQ5FE44ZEQKK2J6/r58CTGtLeQ+UQKEk/QYJJyDVyA3MSKrhqFarT0m7AMu3bTT6w==,iv:JXh6s43A06qHa3NWqr1xbzds+9KE1iMC0qPZZtU/PAk=,tag:O5ykI1vE/R2m9ElatQYbYA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0LzVnQjJpRTVnR3RTNnVF
        cmlJZWNwSlNIdW9EM0JwRmRHMVBHVldGVjAwCjhHL2xPUFgwNjlFeVNsZXRsakw5
        YlJCZnYxdUdEU1ljeDRPY05IRG1haFUKLS0tIHZGQ1B4aSsyT0p2cTQ3YXNJa1ZC
        Z2g1aUNjK2NvaU5LUzBOMDNEUkpuc00KZalnl3W+aqLU53boIabk5ofVZw52mcIp
        S+rHVYvyMfZi2Dwh7nV+AW0CMe/V9XIUN6nlSLp4iPRMaUqWke/LXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T07:18:38Z"
  mac: ENC[AES256_GCM,data:792D5fi6al84bwCyxtI0qX2qQavcqqD/sf8F1AAHqi0BbeqD873zxO7d237CiyHrnDXEiZkuXJy4rbEuBwUdVptA3r9Mo8718iZttPD5ZEOCyeh89u0DwKZb0GVRczUNo2LPRmlbBbf0PGyqwyx2kpsEi1SJau8stlqmFCgfd+w=,iv:zx+EkuZG9BuPAoN+VTwkN4iu8BEpZJP5XEUpB/yCjzs=,tag:g5opwvsBCRsP6/OZcaxYZg==,type:str]
  version: 3.13.1
