kind: Secret
apiVersion: v1
metadata:
  name: harbor-k8s-robot-account-auth
  namespace: harbor
stringData:
  password: ENC[AES256_GCM,data:DZRk24cDmzpgke3FffXz0IJGoe1/7jSMg3zztN6ZSCQ=,iv:hm+E4lR8NS52m/2x3rRCLl0xoOoB1dWcywqPR/wknKU=,tag:WL2oUcRyVE6EA3n1mXcU0A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZ2sydkdrU09tSnRMclhO
        eklVRTB0dkt3V2JzdzJNNXBNUVhqSGVvUjF3CjNPU1NaK3ZGN1k1ZmV4ZmRGa3ZC
        Ymxta0VveWk4VFZoNXpWeUJjYjl5VTgKLS0tIEdYOXBrSHgyTFpDTDdsMlZueDVa
        ZnJOVGcxQjE5ZTg1Ri9GRFVtTE1uVUUKRZ1XWpU7lqrd5H0Cs4j3gwg3mTN+gSSV
        aCK3jOZa0E5EDnpwKDexpVxVFDcf5W7qvdW6HPFzNOmjmBLLZzpWCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-27T05:18:04Z"
  mac: ENC[AES256_GCM,data:29WUh0XPIzce6LuvLtbVuwa1kLA9Jh5fpG6PWB36NB182W5CiVpmlNS+G1qqh75ZWcNCgIf7bai977f/kgnahxq18kWRtImAs/GGQ614cvlbs6QqYF5+bREHWdw1CbXjF0HFf33nNHMDgeq6JiFhrybllQP+YjKi/8I068r9a9M=,iv:gRldUoGiMiFXMAun8d/wOXM+20cfkRzUJ1yqxMU+2k8=,tag:v3QVZQkxhQSLagVSB5YqGA==,type:str]
  version: 3.13.1
