apiVersion: v1
kind: Secret
metadata:
  name: harbor-admin-auth
  namespace: harbor
type: Opaque
stringData:
  HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:6c5SVZ272MzzXPMFd1/Law==,iv:dbYtLGBYD7vjbOzr7riPw4fHGmkJ0O3SAMQjfwBs2Xc=,tag:MpvEuTqKumU54uBjObYC/w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3M0xxRkVJNmdMM3libXRp
        eXljUkprZUJVOVM0VEdHMmZOcWlSWnZ1elZNCjdBcUxRYjgrcXFDdnhGNlZGTE0z
        VWpNN1B5Q1lURFVnYmFVTlRYK2ZNREEKLS0tIENTU1lBcWVLWGsxaEs3TXRSbHlR
        UTBtazJEaExKcXZaQ2NDY0ZzanNFcGcKpG0iY/mpIpVaUj8ynzWzNQQSQXce8B8o
        cZg1ATbCpLWO9FaQpe+NSw9GfR7AHhLRACLJknuLG6r3POCv03DbLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T14:18:11Z"
  mac: ENC[AES256_GCM,data:gFwzRFHghEa3nbW7tvF4T0xCXs7Buc/ow6dheYFzoxltO7QLa6dDxFvzux8+RlB5YH3VZgRlZAzs0WKVq4fpSBVt2vJ3UgTrA0GUZdaKuvusK/3685P9gbMCWfZYZIF1qSQgXZeLkh8IZpkRuTVLejECYjOVIBV+Ld7hRSnCL7I=,iv:TyBS4+YzVvtclDUrstBBE+EhDBqCIZ3Otfh7/POZsMk=,tag:yrEFdG/5S3p40VD4tppuFw==,type:str]
  version: 3.13.1
