---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm-repo.yaml
  - ./helm-release.yaml
  - ./harbor-admin-secret.yaml
  - ./harbor-oidc-secret.yaml
  - ./harbor-redis-auth-secret.yaml
  - ./pg-cluster.yaml
  - ./redis-release.yaml

  - ./git-repository.yaml
  - ./tofu-terraform.yaml
  - ./harbor-k8s-robot-account-auth-secret.yaml
