apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./router.yaml
  - ./msr3600.yaml
  - ./s5624p.yaml
  - ./s5100.yaml
  - ./s5624p-compat.yaml
  - ./s5100-compat.yaml
  - ./role.yaml
  - ./authz-policy.yaml
