apiVersion: v1
kind: Secret
metadata:
  name: harbor-redis-auth
  namespace: harbor
type: Opaque
stringData:
  REDIS_PASSWORD: ENC[AES256_GCM,data:wdJgb28ctEx6uA7nD9SRYg==,iv:lfBXy/VFvho7vUpnWcGcqQH3WEh7VoL3iK3H8VIvOKM=,tag:4tf3bheunrNrzDw6b8vxYw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcHVuYU14NzhwNDBieFlP
        NG01UEpndUVtU09WY1J6T2tRb0d0aXVvcFJRClBSeXdBQnNVNGMxS0NIUHY3STFZ
        S3VnY09ja0h3RHR3RFhPVVBYR1pCSUkKLS0tIGcrTklnczZYY2U5dnUxTDVEMVBl
        RFduYlJwRFVYUG0wTDlyaGtzQ0lFYTgKVpvlgmeu0G7ye90pdcmwrpLzmBk1a9lR
        EncGr5+17QzJD9Coph1Mkks/kegsMrd7KSTVrCgnQ1ePS3NfZoe/Aw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T14:21:22Z"
  mac: ENC[AES256_GCM,data:2b90SLMXjgxVsqEcJcSS1o8j535HTDqjcKEBUlQSIm1OTErvrmwtOwTms3RfoNXMYlWy+kDZYERtWdh3yAOXb/MIjQCIPIx0WJZLcQUQpWz+agNGvttmcV/Q2Fpx4dMKs38WRskhwQkgNn8lCagSEnPIwAaAiFzEfg9eDIFCSxM=,iv:iZAO46W1dKdyNyW7BhWBEdTF2qe7hxivqgy5/30c2lU=,tag:UZOwmYvSRWPGq9tSCNzXtQ==,type:str]
  version: 3.13.1
