---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helm-chart-redis
  namespace: harbor
spec:
  interval: 12h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://dockerproxy.net/bitnamicharts/redis
  ref:
    tag: "25.5.3"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor-redis
  namespace: harbor
spec:
  releaseName: harbor-redis
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: helm-chart-redis
    namespace: harbor
  # https://github.com/bitnami/charts/tree/main/bitnami/redis
  values:
    architecture: standalone

    auth:
      enabled: true
      existingSecret: harbor-redis-auth
      existingSecretPasswordKey: REDIS_PASSWORD

    master:
      resources:
        limits:
          cpu: 500m
          memory: 2Gi
        requests:
          cpu: 10m
          memory: 10Mi

      persistence:
        enabled: true
        size: 512Mi
        sizeLimit: 10Gi
        storageClass: "local-path-nocow"
    
    commonConfiguration: |
      appendonly yes
      aof-use-rdb-preamble yes
      maxmemory 1600mb
      maxmemory-policy volatile-lru
      slowlog-log-slower-than 10000
      slowlog-max-len 128

    metrics:
      ## @param metrics.enabled Start a sidecar prometheus exporter to expose Redis(R) metrics
      ##
      enabled: enabled
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
        limits:
          cpu: 100m
          memory: 512Mi
      serviceMonitor:
        enabled: true
        namespace: "" # Use current ns
