# Request a wildcard certificate for the target domain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: i319-reroute-tls
spec:
  secretName: i319-reroute-tls-secret
  issuerRef:
    name: letsencrypt-infra
    kind: ClusterIssuer
  dnsNames:
  - "*.clustername.319.ccsn.dev"
  - "*.319.ccsn.dev"
  - "*.319.staging.ccsn.dev"
