---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./nginx-config.yaml
  - ./nginx-subconfig.yaml
  - ./cert.yaml
  - ./deployment.yaml
  - ./service.yaml

namespace: i319-reroute
