apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-01-secret-infra
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:W0ToownHyrw3MzowkzVv5Q8Vs5LsCkTC+WfzQrxI898uxUl/X7O5xD9a9pfrqN908SBts4U=,iv:CKTc4MI1nSfzj1OJcs2BpQD0Op34MXV2En+PTGptoUE=,tag:WLd/zP5ZOR5Bg5NbknxvdQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOVdOWlJCS2JNUUZVdzUz
        MEVWdEFhVHl1QmNWMG04Mms4czNYbFZzOWk4Ck1WN1BhRk5lODZaVzB4QldCTElu
        MEl6WFJMRXdsc01KdXAzYUI5RlRXWUkKLS0tIEplQjZ5WFhRbDdncG4zZ0M1OWFa
        T2tXNFRya3MyMERmNVBDUisya0pyM0kKo+ZphGKADMxwWRqJdophGAztfIc4bS43
        dLhnJoV7WHn19Nl0OS6ys8wEhP/+tiw0p1IfDc8+QospoE5mN7FZIA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T16:20:46Z"
  mac: ENC[AES256_GCM,data:VVYG+MSCj200V4c5cFJ6ptFN5J8RjJoinlFpg02yGC2lH5z8t/J3vHf5vL0nJwC4i1wAtEz45/w7sN+4m9SajiNCJz1sydV6VCTeWR27LLkr9dV+mGMG0tzWmsLmWpHvBYOUux2/5TZ9eozU4sVWhR0nu9JjacN1YnxJm+V/+u4=,iv:G9CWU8k2HlOj3xtrgsiBgaKv8OJA9D/DO/pmXkcKzpE=,tag:7vnAatbXXySDrYeuy0/m6w==,type:str]
  version: 3.13.1
