apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-01-secret-staging
  namespace: staging
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:xzHONknQ0YwME3GdQnnYad4tW9AtLA8wfbuxigh5lVOEXhX1GgvI35vlMRpXCfOf4mCSrmM=,iv:dF9qeU+6O2CdbZseJOlL/9icLpSZVwTgRacXUXaIexg=,tag:nKMgHI5g1HYjnWXdXbWUzQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTXUzWVBYd0JrQzJDZDcy
        K0dETnFxcnkrZVJiQUErQVgwNStsdHJma21VCnhKWkNKQmt6WXo1dTFlVXNzU2JQ
        T3dXYWRha2VodGNINnV5K3dwWSthUVUKLS0tIG4rVUtPN2pvNjdyU241Z01yRkhR
        dnpnREg4V1RBV0wyUFJUbWJST1IwaTQKzuoqBTRXFquDBpTLy8kQA4z71OfzIyLi
        7Gw9n7hFG6PtlJ3I9OnTnfT/wLW2oll8HwSze5ns2tzihepN6r4aUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T16:21:00Z"
  mac: ENC[AES256_GCM,data:Y53Mq1JKQjnQc+niD/A1i0hrK0cQsxspsJ0O3JPUhDg+iFoNGKCS90ZlsCZ37b5Op0c69wW5b6jalGUNHYIv/j3i496PWRdwkVBKBuHn+dQKOEe+1JZwbpGuw8P2M16K+H0HYt3oxmwqsHZm9tr2qz2aM1zUN0KqRNbMDh43jF0=,iv:q2b9HSG1m8WXaUDHWYX65QvzhWMKRdg3VZNTnGDsBm4=,tag:kJJ1roMCYU/azooGcTrxOA==,type:str]
  version: 3.13.1
