apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-01-secret-prod
  namespace: prod
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:japZsoIcm3tncK+qhfqDIrNNz9pRc6EayRA2iwkXLGusdH2PzMLwewjNEZjGMbe9YZQu0Zo=,iv:DXJdAvK1h0OePZPV7/OP3C220+8r+ihcO6YomJ9uQz8=,tag:YTUXIQIZ/wXQ7vRIQ9EnMA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdExiRXVOaTV4cmhjd3NR
        T2VVOHphSlc3blZmbmF3NWc2dGtheDNmOW53CmpTM3FYb2ZveS93dS90V3UzWURq
        d2lFTnNXbEh0YUVOWHZYZ3BCU2pFSU0KLS0tIGFodVl0WVE3dWhMMnZPN21naTE1
        VXZFWkpWdTNaZXVaMXNTenZzSWc3NDgKydm9wIj8b/kVBbufoWKUt5D5t1FTIsxA
        e9DWoMnDD7jwINYg8ayInz0eTwopob7GrKTZhp6TwvjQNXe8+8LPQg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T16:20:54Z"
  mac: ENC[AES256_GCM,data:iHScUtvGY4AoTTnWJeUtbPYcSBkn+Q/TGVjXp9OFGf97bsR3Bb5z5JTwBM36s2lsffKAn3ezAyMlOY/XbI0+8xbAoAu2I9uSIpIId098B0E2QW3xn6X5DWaHzDM8kWaKKksAcSdSP4wZVSc+rEbKqmxmgJcfGFrlS+gjmOPr0ss=,iv:h8NoDHwnCk/bRqF3rjwUwLSz8FnLjlSwAdXoaTQ3E2Y=,tag:FfGPrGYD9QH6R1YwBeaKOA==,type:str]
  version: 3.13.1
