kind: Secret
apiVersion: v1
metadata:
  name: flux-oauth
  namespace: flux-system
stringData:
  client-id: ENC[AES256_GCM,data:q+nYzcI=,iv:/QpN6vapJb1jSayY6zNKFlGc4TwHz3dv7JAauH7yBSs=,tag:18n2bbUPo3PdTf7md94KRQ==,type:str]
  client-secret: ENC[AES256_GCM,data:2gcW6sY=,iv:zysOzaNLNCTe36hDGZ78nVm9xtChd9NK3Ujhoh696Dc=,tag:rHrvI/B/SI9m25I/HJKAkw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaW1qWmdScUYzNlpGL0RR
        eEtnU3ZaazNkVXFjblhWMEJyb0dRZWRrM2hFCkpMT0R3S2FabU9oZkp0MXF4WFUr
        S1k3cm1ER3FOUFFHZWtYcHVTSTlSK1kKLS0tIDcrOUdxQmMveU8vTXo5VXBhYTht
        bElEYy94cXBFbjNxQ25qVkNHL3RkWFUKYhQ6OJHhJjPrvlCY7hfk49bp2TQvTyCQ
        w1XiSugvPj6tfRkha8OgVQWEzXJD0Llae5mHKekdD6jDBL9ufV7AlA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-27T05:19:28Z"
  mac: ENC[AES256_GCM,data:LWGAYnNBdmFiGYHR+nFmIjGHufwUCIU5tz+G4HUo2bKYkS0/BQ289qv0e5Jo8aH7OswEHMCIGAEiKGHcpwM4Qb0q3eRblQmHwKzeTgYnvFsvljws8TU1bJR+22cQd76/X4t6hB2//g629VbjP7MFET2wriZuRtuQ3CHLdvxZg9A=,iv:37l0d70aQBrEhPNhTqhUebT7iXbFE9qZla/U6lMBCW0=,tag:0vGcp87ms56aO9S7IOcesQ==,type:str]
  version: 3.13.1
