kind: Secret
apiVersion: v1
metadata:
  name: flux-oauth
  namespace: flux-system
stringData:
  client-id: ENC[AES256_GCM,data:hmujTNZJTQakrsVwecn5uQtlOuV7,iv:OFLVNK2lOFjtPQ07iYF/1i44sVPDXkLCS464AP3ZG/o=,tag:XU5jbqvPPuygG9yL6M/z4A==,type:str]
  client-secret: ENC[AES256_GCM,data:grZee7k+ADguaS2MLZBMZ10B/OGoUcij1VeVdTWj5m4=,iv:eF9rPlzlYqBwyNvbj4wrz04g3zpUlTXrHpvbKfXdBBQ=,tag:oSWsEsgTwRJLKmmZb5PnBw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMnJPUnJwRlBoUGR2ZUcr
        RGxVZnQyQVQxaGZsMGExYUNUbC9OSXN0cUFNCmhmdkZobGZTbU1lSERvRmtVV3Bq
        VVFLY3U0aEY0c3orQ0RZbk9lcXQ5WkUKLS0tIDV2MjVJVVgzS1E4TXgvTW9QQ25m
        N1VzamtJU0RoYXdQTkpKUHNBTEs2QjgKtuKLydjWyxngfK4W2dNW88guFcyobQNh
        E7eHq9RWRcjm3dzGZh+tvC+54mK+1R8J/P6lx+kLtkTeSdd7RX34PA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1td0htsklm8xpsvcync3ulwxs82w5a9a03eeq9wwg8pm2mx3t99fqtgyhhs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T06:59:25Z"
  mac: ENC[AES256_GCM,data:m2GhGothncYgxQw1CsHcAEwYNt4Dldd12HyIPNIPphTLl4pInTGu5lRY3lN/k3U1LXl1RVcK4/YcnImwde0f/uyZdrcgcWl2vTsz0VWbKau/OKjJX8HvyF5fGZvQ4btzZGQYS7SfwfV0ld9OBymG7ZadEgdZw76hOIryDlbHRqM=,iv:DMGOhusOPrwmSz4XpYl9gi7ATKcAbuTHzzldeI/Hm34=,tag:0DkO22KfikHX9+TdsOXmbw==,type:str]
  version: 3.13.1
