# https://fluxcd.io/flux/components/helm/helmreleases/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  releaseName: flux-operator
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: helm-chart-flux-operator
    namespace: flux-system
  values:
    web:
      config:
        baseURL: https://flux.ccsn.dev
        authentication:
          type: OAuth2
          oauth2:
            provider: OIDC
            issuerURL: https://login.ccsn.dev/oidc
            scopes:
              - openid
              - profile
              - offline_access
              - roles
            # Isolate with "flux:" prefix to avoid accidental impersonation by other users in the system.
            variables:
                # Username can be null, so we fallback to sub claim with "flux:uid:" prefix to ensure uniqueness and avoid role escalation.
                # IdP depended: Logto doesn't expect `:` to exist in username, so that we are able to use `:` as a separator.
                # If your IdP allows `:` in username, you may need to choose a different separator and adjust the expression accordingly.
              - name: username
                expression: '(has(claims.username) && type(claims.username) == string) ? "flux:" + string(claims.username) : "flux:uid:" + claims.sub'
              #   # IdP depended: Logto doesn't generate `:` in sub claim, so that we are able to isolate flux users with "flux:" prefix.
              #   # If your IdP generates `:` in sub claim, you may need to write a more complex expression to isolate flux users.
              # - name: uid
              #   expression: '"flux:" + claims.sub'
              - name: groups
                expression: |
                  !has(claims.roles) ? [] :
                    type(claims.roles) == list ? 
                      dyn(claims.roles).filter(r, r.startsWith("flux:")) : 
                    type(claims.roles) == string ? 
                      string(claims.roles).split(",").filter(r, r.startsWith("flux:")) : 
                    []
            profile:
              name: "(has(claims.name) && type(claims.username) == string) ? claims.name : ((has(claims.username) && type(claims.username) == string) ? claims.username : claims.sub)"
            impersonation:
              username: "variables.username"
              # Seems like Flux doesn't support impersonating uid yet.
              # uid: "variables.uid"
              groups: "variables.groups"
        userActions:
          # Send audit events to Kubernetes and Flux's notification-controller.
          # Optional. Disabled by default. Special value ["*"] enables all actions.
          audit:
            - "*"
            
  valuesFrom:
    - kind: Secret
      name: flux-oauth
      valuesKey: client-id
      targetPath: web.config.authentication.oauth2.clientID
    - kind: Secret
      name: flux-oauth
      valuesKey: client-secret
      targetPath: web.config.authentication.oauth2.clientSecret
